package crypto.forestfish.enums.evm;

public enum BSCERC721Token {

	// Gaming
	OUTERRINGMMO_WEAPON,
	OUTERRINGMMO_ARMOR,
	OUTERRINGMMO_LANDVEH,
	OUTERRINGMMO_SPACEVEH,
	OUTERRINGMMO_EXOCRED,
	DREAMCARD,
	STELLAFANTASY_ASSET
}
