package crypto.forestfish.evm;

import java.util.HashMap;

import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.web3j.protocol.Web3j;
import org.web3j.protocol.http.HttpService;

import crypto.forestfish.enums.evm.EVMChain;
import crypto.forestfish.objects.evm.model.chain.EVMChainInfo;
import crypto.forestfish.objects.evm.model.chainext.ExtEVMChainEntry;
import crypto.forestfish.utils.EVMUtils;
import crypto.forestfish.utils.FilesUtils;
import crypto.forestfish.utils.HttpRequestUtils;
import crypto.forestfish.utils.JSONUtils;
import crypto.forestfish.utils.SystemUtils;

public class CheckNewEVMNodeCandidates {

	private static final Logger LOGGER = LoggerFactory.getLogger(CheckNewEVMNodeCandidates.class);

	@SuppressWarnings("serial")
	@Test
	public void check() {

		boolean debug = false;

		HashMap<String, EVMChain> chain_map = new HashMap<String, EVMChain>() {{
			this.put("Kroma", EVMChain.KROMA);
			this.put("Cronos Testnet", EVMChain.CRONOSTEST);
			this.put("PLAYA3ULL GAMES", EVMChain.PLAYA3ULL);
			this.put("zkSync Sepolia Testnet", EVMChain.ZKSYNCERASEPOLIATEST);
			this.put("Ethereum Mainnet", EVMChain.ETH);
			this.put("Goerli", EVMChain.GOERLITEST);
			this.put("Ubiq", EVMChain.UBIQ);
			this.put("OP Mainnet", EVMChain.OPTIMISM);
			this.put("Metadium Mainnet", EVMChain.METADIUM);
			this.put("Metadium Testnet", EVMChain.METADIUMTEST);
			this.put("Cronos Mainnet", EVMChain.CRONOS);
			this.put("KardiaChain Mainnet", EVMChain.KARDIACHAIN);
			this.put("Boba Network Rinkeby Testnet", EVMChain.BOBARINKEBYTEST);
			this.put("LUKSO Mainnet", EVMChain.LUKSO);
			this.put("BNB Smart Chain Mainnet", EVMChain.BSC);
			this.put("Syscoin Mainnet", EVMChain.SYSCOIN);
			this.put("Ethereum Classic Mainnet", EVMChain.ETC);
			this.put("Ethereum Classic Testnet Mordor", EVMChain.ETCMORDORTEST);
			this.put("TomoChain", EVMChain.TOMOCHAIN);
			this.put("TomoChain Testnet", EVMChain.TOMOCHAINTEST);
			this.put("Gnosis", EVMChain.GNOSIS);
			this.put("Shibarium", EVMChain.SHIBARIUM);
			this.put("OKExChain Testnet", EVMChain.OKXTEST);
			this.put("OKXChain Mainnet", EVMChain.OKX);
			this.put("Conflux eSpace (Testnet)", EVMChain.CONFLUXTEST);
			this.put("Conflux eSpace", EVMChain.CONFLUX);
			this.put("Bitkub Chain", EVMChain.BITKUB);
			this.put("BNB Smart Chain Testnet", EVMChain.BSCTEST);
			this.put("Aurora Mainnet", EVMChain.AURORA);
			this.put("Aurora Testnet", EVMChain.AURORATEST);
			this.put("Sepolia", EVMChain.SEPOLIATEST);
			this.put("Etho Protocol", EVMChain.ETHO);
			this.put("zKatana", EVMChain.ZKATANATEST);
			this.put("Scroll", EVMChain.SCROLL);
			this.put("Scroll Sepolia Testnet", EVMChain.SCROLLSEPOLIATEST);
			this.put("Scroll Alpha Testnet", EVMChain.SCROLLALPHATEST);
			this.put("Arbitrum Goerli", EVMChain.ARBITRUMGOERLITEST);
			this.put("Japan Open Chain Mainnet", EVMChain.JOC);
			this.put("Japan Open Chain Testnet", EVMChain.JOCTEST);
			this.put("Arbitrum Sepolia", EVMChain.ARBITRUMSEPOLIATEST);
			this.put("Milkomeda A1 Testnet", EVMChain.MILKOMEDAA1TEST);
			this.put("Milkomeda C1 Testnet", EVMChain.MILKOMEDAC1TEST);
			this.put("Taiko Jolnir L2", EVMChain.TAIKOALPHA5TEST);
			this.put("Taiko (Alpha-2 Testnet)", EVMChain.TAIKOALPHA2TEST);
			this.put("Base Goerli Testnet", EVMChain.BASEGOERLITEST);
			this.put("Base Sepolia Testnet", EVMChain.BASESEPOLIATEST);
			this.put("OP Sepolia Testnet", EVMChain.OPTIMISMSEPOLIATEST);
			this.put("Zilliqa EVM", EVMChain.ZILLIQA);
			this.put("Zilliqa EVM Testnet", EVMChain.ZILLIQATEST);
			this.put("Beam", EVMChain.BEAM);
			this.put("Mumbai", EVMChain.MUMBAITEST);
			this.put("Linea", EVMChain.LINEA);
			this.put("Linea Testnet", EVMChain.LINEATEST);
			this.put("Avalanche C-Chain", EVMChain.AVAX);
			this.put("Avalanche Fuji Testnet", EVMChain.FUJITEST);
			this.put("Oasis Emerald", EVMChain.OASISEMERALD);
			this.put("Oasis Emerald Testnet", EVMChain.OASISEMERALDTEST);
			this.put("Celo Mainnet", EVMChain.CELO);
			this.put("Arbitrum One", EVMChain.ARBITRUMONE);
			this.put("OasisChain Mainnet", EVMChain.OASISCHAIN);
			this.put("Bitkub Chain Testnet", EVMChain.BITKUBTEST);
			this.put("Oasis Sapphire", EVMChain.OASISSAPPHIRE);
			this.put("Oasis Sapphire Testnet", EVMChain.OASISSAPPHIRETEST);
			//this.put("Astar zkEVM", EVMChain.ASTARZKEVM);
			this.put("Evmos", EVMChain.EVMOS);
			this.put("Evmos Testnet", EVMChain.EVMOSTEST);
			this.put("Base", EVMChain.BASE);
			this.put("Klaytn Mainnet Cypress", EVMChain.KLAYTN);
			this.put("Shardeum Liberty 1.X", EVMChain.SHARDEUMLIBERTY1xTEST);
			this.put("Shardeum Liberty 2.X", EVMChain.SHARDEUMLIBERTY2xTEST);
			this.put("Shardeum Sphinx 1.X", EVMChain.SHARDEUMSPHINX1xTEST);
			this.put("Canto", EVMChain.CANTO);
			this.put("Canto Tesnet", EVMChain.CANTOTEST);
			this.put("opBNB Testnet", EVMChain.OPBNBTEST);
			this.put("Mantle Testnet", EVMChain.MANTLETEST);
			this.put("LUKSO Testnet", EVMChain.LUKSOTEST);
			this.put("Fantom Testnet", EVMChain.FANTOMTEST);
			this.put("ZetaChain Athens 3 Testnet", EVMChain.ZETAATHENSTEST);
			this.put("Milkomeda C1 Mainnet", EVMChain.MILKOMEDAC1);
			this.put("Milkomeda A1 Mainnet", EVMChain.MILKOMEDAA1);
			this.put("Tenet", EVMChain.TENET);
			this.put("Polygon zkEVM Testnet", EVMChain.ZKEVMTEST);
			this.put("WEMIX3.0 Mainnet", EVMChain.WEMIX);
			this.put("PulseChain", EVMChain.PULSECHAIN);
			this.put("zkSync Era Mainnet", EVMChain.ZKSYNCERA);
			this.put("Hedera Mainnet", EVMChain.HEDERA);
			this.put("Hedera Testnet", EVMChain.HEDERATEST);
			this.put("Boba Network", EVMChain.BOBA);
			this.put("Fantom Opera", EVMChain.FANTOM);
			this.put("opBNB Mainnet", EVMChain.OPBNB);
			this.put("Tenet Testnet", EVMChain.TENETTEST);
			this.put("Polygon Mainnet", EVMChain.POLYGON);
			this.put("Syscoin Tanenbaum Testnet", EVMChain.SYSCOINTEST); 
			this.put("Xpla Mainnet", EVMChain.XPLA); 
			this.put("Zora", EVMChain.ZORA);
			this.put("Zora Sepolia Testnet", EVMChain.ZORASEPOLIATEST);
			this.put("Moonbeam", EVMChain.MOONBEAM); 
			this.put("Moonriver", EVMChain.MOONRIVER); 
			this.put("Mantle", EVMChain.MANTLE); 
			this.put("Immutable zkEVM Testnet", EVMChain.IMMUTABLEZKEVMTEST); 
			this.put("ZKFair Testnet", EVMChain.ZKFAIRTEST); 
			this.put("Manta Pacific Testnet", EVMChain.MANTATEST);
			this.put("Neon EVM Mainnet", EVMChain.NEON);
			this.put("FNCY Testnet", EVMChain.FNCYTEST);
			this.put("FNCY", EVMChain.FNCY);
			this.put("Dogechain Mainnet", EVMChain.DOGECHAIN);
			this.put("Dogechain Testnet", EVMChain.DOGECHAINTEST);
			this.put("WEMIX3.0 Testnet", EVMChain.WEMIXTEST);
			this.put("Metis Goerli Testnet", EVMChain.METISGOERLITEST);
			this.put("Boba BNB Mainnet", EVMChain.BOBABNB); 
			this.put("Siberium Network", EVMChain.SIBERIUM);
			this.put("Siberium Test Network", EVMChain.SIBERIUMTEST); 
			this.put("Kava Testnet", EVMChain.KAVATEST); 
			this.put("Kava", EVMChain.KAVA); 
			this.put("Syscoin Tanenbaum Testnet", EVMChain.SYSCOINTEST);
			this.put("Flare Mainnet", EVMChain.FLARE); 
			this.put("ShibaChain", EVMChain.SHIBACHAIN); 
			this.put("Ethereum Classic", EVMChain.ETC); 
			this.put("XDC Network", EVMChain.XDC); 
			this.put("XDC Apothem Network", EVMChain.XDCAPOTHEMTEST);
			this.put("Telos EVM Mainnet", EVMChain.TELOS);
			this.put("Telos EVM Testnet", EVMChain.TELOSTEST);
			this.put("Polygon zkEVM", EVMChain.ZKEVM);
			this.put("Core Blockchain Mainnet", EVMChain.CORE);
			this.put("Core Blockchain Testnet", EVMChain.CORETEST);
			this.put("Rangers Protocol Mainnet", EVMChain.RANGERS);
			this.put("Rangers Protocol Testnet", EVMChain.RANGERSTEST);
			this.put("Kroma Sepolia", EVMChain.KROMASEPOLIATEST);
			this.put("DeFiChain EVM Network Mainnet", EVMChain.DEFICHAIN);
			this.put("DeFiChain EVM Network Testnet", EVMChain.DEFICHAINTEST);
			this.put("Torus Mainnet", EVMChain.TORUS);
			this.put("Torus Testnet", EVMChain.TORUSTEST);
			this.put("Quadrans Blockchain", EVMChain.QUADRANS);
			this.put("Quadrans Blockchain Testnet", EVMChain.QUADRANSTEST);
			this.put("Rootstock Mainnet", EVMChain.ROOTSTOCK);
			this.put("Rootstock Testnet", EVMChain.ROOTSTOCKTEST);
			this.put("PulseChain Testnet v4", EVMChain.PULSECHAIN4TEST);
			this.put("ZKFair Mainnet", EVMChain.ZKFAIR);
			this.put("Hypra Mainnet", EVMChain.HYPRA);
			this.put("Eluvio Content Fabric", EVMChain.ELUVIO);
			this.put("Bitgert Mainnet", EVMChain.BITGERT);
			this.put("Mind Smart Chain Mainnet", EVMChain.MINDSMARTCHAIN);
			this.put("Mind Smart Chain Testnet", EVMChain.MINDSMARTCHAINTEST);
			this.put("Unique", EVMChain.UNIQUE);
			this.put("Quartz by Unique", EVMChain.QUARTZUNIQUE);
			this.put("Rise of the Warbots Testnet", EVMChain.ROTWTEST);
			this.put("SOMA Network Testnet", EVMChain.SOMATEST);
			this.put("Edgeware EdgeEVM Mainnet", EVMChain.EDGEWARE);
			this.put("Ontology Mainnet", EVMChain.ONTOLOGY);
			this.put("Ontology Testnet", EVMChain.ONTOLOGYTEST);
			this.put("Holesky", EVMChain.HOLESKYTEST);
			this.put("Bifrost Mainnet", EVMChain.BIFROST);
			this.put("Bifrost Testnet", EVMChain.BIFROSTTEST);
			this.put("Fibonacci Mainnet", EVMChain.FIBONACCI);
			this.put("W3Gamez Holesky Testnet", EVMChain.W3GAMEZTEST);
			this.put("EIOB Mainnet", EVMChain.EIOB);
			this.put("Kinto Mainnet", EVMChain.KINTO);
			this.put("LiquidLayer Mainnet", EVMChain.LIQUIDLAYER);
			this.put("LiquidLayer Testnet", EVMChain.LIQUIDLAYERTEST);
			this.put("Jono11 Subnet", EVMChain.JONO11);
			this.put("Jono12 Subnet", EVMChain.JONO12);
			this.put("ZKAmoeba Testnet", EVMChain.ZKAMOEBATEST);
			this.put("Filecoin - Mainnet", EVMChain.FILECOIN);
			this.put("Filecoin - Calibration testnet", EVMChain.FILECOINCALIBRATIONTEST);
			this.put("Eclipse Subnet", EVMChain.ECLIPSETEST);
			this.put("Innovator Chain", EVMChain.INOV8);
			this.put("ZKAmoeba Testnet", EVMChain.ZKAMOEBATEST);
			this.put("Mordor Testnet", EVMChain.ETCMORDORTEST);
			this.put("Manta Pacific Mainnet", EVMChain.MANTA);
			this.put("Metis Andromeda Mainnet", EVMChain.METIS);
			this.put("Mantle Sepolia Testnet", EVMChain.MANTLESEPOLIATEST);
			this.put("Metis Stardust Testnet", EVMChain.METISSTARDUSTTEST);
			this.put("Alph Network", EVMChain.ALPH);
			this.put("Berachain Artio", EVMChain.BERACHAINARTIOTEST);
			this.put("Nexa Block", EVMChain.NEXABLOCKTEST);
			this.put("Blast Sepolia Testnet", EVMChain.BLASTSEPOLIATEST);
			this.put("Bitfinity Network Testnet", EVMChain.BITFINITYTEST);
			this.put("Cosvm Mainnet", EVMChain.COSVM);
			this.put("BST Chain", EVMChain.BSTCHAIN);
			this.put("AlveyChain Mainnet", EVMChain.ALVEYCHAIN);
			this.put("Ancient8", EVMChain.ANCIENT8);
			this.put("Ancient8 Testnet", EVMChain.ANCIENT8TEST);
			this.put("Ancient8 Testnet", EVMChain.ANCIENT8TEST);
			this.put("MAPO Makalu", EVMChain.MAPPROTOCOLTEST);
			this.put("MAP Protocol", EVMChain.MAPPROTOCOL);
			this.put("BEVM Testnet", EVMChain.BEVMTEST);
			this.put("Puppynet Shibarium", EVMChain.SHIBARIUMPUPPYNETTEST);
			this.put("DOID", EVMChain.DOID);
			this.put("DOID Testnet", EVMChain.DOIDTEST);
			this.put("BPX Blockchain", EVMChain.BPX);
			this.put("Lovely Network Testnet", EVMChain.LOVELYTEST);
			this.put("Lovely Network Mainnet", EVMChain.LOVELY);
			this.put("Mint Testnet", EVMChain.MINTTEST);
			this.put("ZetaChain Mainnet", EVMChain.ZETA);
			this.put("Vrcscan Mainnet", EVMChain.VRCSCAN);
			this.put("Xenon Chain Testnet", EVMChain.XENONTEST);
			this.put("Lisk Sepolia Testnet", EVMChain.LISKTEST);
			this.put("MetaDAP Enterprise Mainnet", EVMChain.METADAP);
			this.put("MetaDAP Enterprise Testnet", EVMChain.METADAPTEST);
			this.put("Bloom Genesis Testnet", EVMChain.BLOOMTEST);
			this.put("Bloom Genesis Mainnet", EVMChain.BLOOM);
			this.put("Sei Devnet", EVMChain.SEIDEVTEST);
			this.put("PowerGold", EVMChain.AURORAPOWERGOLD);
			this.put("Syndr L3 Sepolia", EVMChain.SYNDRTEST);
			this.put("Dymension", EVMChain.DYMENSION);
			this.put("Elizabeth Testnet", EVMChain.TIMETEST);
			this.put("Merlin Mainnet", EVMChain.MERLIN);
			this.put("ZKSats Mainnet", EVMChain.ZKSATS);
			this.put("Syndicate Frame Chain", EVMChain.FRAMECHAIN);
			this.put("Nexa Mainnet Block", EVMChain.NEXABLOCK);
			this.put("Nexa Testnet Block", EVMChain.NEXABLOCKTEST);
			this.put("unreal", EVMChain.UNREAL);
			this.put("Plume Testnet", EVMChain.PLUMETEST);
			this.put("Swan Saturn Testnet", EVMChain.SWANCHAINTEST);
			this.put("Viridis Testnet", EVMChain.VIRIDISTEST);
			this.put("Viridis Mainnet", EVMChain.VIRIDIS);
			this.put("CheckDot Blockchain Devnet", EVMChain.CHECKDOTTEST);
			this.put("Karak Mainnet", EVMChain.KARAK);
			this.put("Karak Testnet", EVMChain.KARAKTEST);
			this.put("Polygon zkEVM Cardona Testnet", EVMChain.POLYGONCARDONATEST);
			this.put("Emoney Network Testnet", EVMChain.EMONEYTEST);
			this.put("Orenium Testnet Protocol", EVMChain.ORENIUMTEST);
			this.put("Dela Sepolia Testnet", EVMChain.DELATEST);
			this.put("Aternos", EVMChain.ATERNOS);
			this.put("C4EI", EVMChain.C4EI);
			this.put("Vanguard", EVMChain.VANGUARDTEST);
			this.put("Hizoco mainnet", EVMChain.HIZOCO);
			this.put("GitSwarm Test Network", EVMChain.GITSWARMTEST);
			this.put("Songbird Testnet Coston", EVMChain.FLARECOSTONTEST);
			this.put("Flare Testnet Coston", EVMChain.FLARECOSTONTEST); 
			this.put("Flare Testnet Coston2", EVMChain.FLARECOSTON2TEST); 
			this.put("Rupaya Testnet", EVMChain.RUPAYATEST); 
			this.put("MetaChain Istanbul", EVMChain.METACHAIN);
			this.put("Vitruveo Mainnet", EVMChain.VITRUVEO);
			this.put("Whitechain", EVMChain.WHITECHAIN);
			this.put("Whitechain Testnet", EVMChain.WHITECHAINTEST);
			this.put("Selendra Network Testnet", EVMChain.SELENDRATEST);
			this.put("Selendra Network Mainnet", EVMChain.SELENDRA);
			this.put("Gold Chain", EVMChain.GOLD);
			this.put("Vitruveo Testnet", EVMChain.VITRUVEOTEST);
			this.put("KONET Mainnet", EVMChain.KONET);
			this.put("Titan (TKX) Testnet", EVMChain.TITANTEST);
			this.put("Decentraconnect Social", EVMChain.DECENTRACONNECT);
			this.put("AlveyChain Testnet", EVMChain.ALVEYCHAINTEST);
			this.put("GUNZ Testnet", EVMChain.GUNZTEST);
			this.put("Masa Testnet", EVMChain.MASATEST);
			this.put("Bitlayer Testnet", EVMChain.BITLAYERTEST);
			this.put("Fraxtal", EVMChain.FRAXTAL);
			this.put("Runic Chain Testnet", EVMChain.RUNICTEST);
			this.put("Ethereum Inscription Mainnet", EVMChain.ETHEREUMINS);
			this.put("APEX Testnet", EVMChain.APEXTEST);
			this.put("Blast", EVMChain.BLAST);
			this.put("Auroria Testnet", EVMChain.AURORIATEST);
			this.put("DeepL Mainnet", EVMChain.DEEPL);
			this.put("DeepL Testnet", EVMChain.DEEPLTEST);
			this.put("Tiltyard Mainnet Subnet", EVMChain.TILTYARD);
			this.put("Astar zKyoto", EVMChain.ASTARZKYOTO);
			this.put("Autonity Bakerloo (Sumida) Testnet", EVMChain.AUTONITYBAKERLOOTEST);
			this.put("Autonity Piccadilly (Sumida) Testnet", EVMChain.AUTONITYPICCADILLYTEST);
			this.put("FlowEVM PreviewNet", EVMChain.FLOWEVM);
			this.put("inEVM Mainnet", EVMChain.INEVM);
			this.put("Astar zkEVM", EVMChain.ASTARZKEVM);
			this.put("CrossFi Testnet", EVMChain.CROSSFITEST);
			this.put("DisChain", EVMChain.DISCHAIN);
			this.put("ZetaChain Mainnet", EVMChain.ZETA);
			this.put("zkLink Nova Mainnet", EVMChain.ZKLINK);
			this.put("zkLink Nova Goerli Testnet", EVMChain.ZKLINKGOERLITEST);
			this.put("Degen Chain Gas Token", EVMChain.DEGEN);
			this.put("Viction", EVMChain.VICTION);
			this.put("Viction Testnet", EVMChain.VICTIONTEST);
			this.put("SoraAI Testnet", EVMChain.SORAAITEST);
			this.put("FileFileGo", EVMChain.FILEFILEGO);
			this.put("Qitmeer Network Mainnet", EVMChain.QITMEER);
			this.put("MAXI Chain Testnet", EVMChain.MAXITEST);
			this.put("Doric Network", EVMChain.DORIC);
			this.put("Reya Network", EVMChain.REYA);
			this.put("Hubble Exchange", EVMChain.HUBBLE);
			this.put("Atleta Testnet", EVMChain.ATLETATEST);
			this.put("HYCHAIN", EVMChain.HYCHAIN);
			this.put("SIC Testnet", EVMChain.SICTEST);
			this.put("Coordinape Testnet", EVMChain.COORDINAPETEST);
			this.put("Charmverse Testnet", EVMChain.CHARMVERSETEST);
			this.put("Superloyalty Testnet", EVMChain.SUPERLOYALTYTEST);
			this.put("Orenium Mainnet Protocol", EVMChain.ORENIUM);
			this.put("IOTA EVM", EVMChain.IOTA);
			this.put("SuperLumio", EVMChain.SUPERLUMIO);
			this.put("Larissa Chain", EVMChain.LARISSA);
			this.put("BEVM Mainnet", EVMChain.BEVM);
			this.put("HYCHAIN Testnet", EVMChain.HYCHAINTEST);
			this.put("Swamps L2", EVMChain.SWAMPS);
			this.put("Electroneum Mainnet", EVMChain.ELECTRONEUM);
			this.put("Amoy", EVMChain.AMOYTEST);
			this.put("Global Trust Network", EVMChain.GLOBAL);
			this.put("Creditcoin Testnet", EVMChain.CREDITCOINTEST);
			this.put("Stratis Mainnet", EVMChain.STRATIS);
			this.put("Galadriel Testnet", EVMChain.GALADRIELTEST);
			this.put("Manta Pacific Sepolia Testnet", EVMChain.MANTASEPOLIATEST);
			this.put("Stability Testnet", EVMChain.STABILITYTEST);
			this.put("0xHash Testnet", EVMChain.HASHTEST);
			this.put("Degen Chain", EVMChain.DEGEN);
			this.put("CamDL Testnet", EVMChain.CAMDLTEST);
			this.put("TAPROOT Mainnet", EVMChain.TAPROOT);
			this.put("Egochain", EVMChain.EGOCHAIN);
			this.put("Arcturus Testneet", EVMChain.ARCTURUSTEST);
			this.put("Espento Mainnet", EVMChain.ESPENTO);
			this.put("Santiment Intelligence Network", EVMChain.SANTIMENT);
			this.put("Quantum Network", EVMChain.QUANTUM);
			this.put("CAGA crypto Ankara testnet", EVMChain.CAGA);
			this.put("Unit Zero Stagenet", EVMChain.UNIT0STAGETEST);
			this.put("re.al", EVMChain.REAL);
			this.put("YMTECH-BESU Testnet", EVMChain.YMTECHBESUTEST);
			this.put("Galadriel Devnet", EVMChain.GALADRIELTEST);
			this.put("Hemi Sepolia", EVMChain.HEMI);
			this.put("DeBank Sepolia Testnet", EVMChain.DEBANKTEST);
			this.put("WorldLand Mainnet", EVMChain.WORLDLAND);
			this.put("Roburna Mainnet", EVMChain.ROBURNA);
			this.put("Roburna Testnet", EVMChain.ROBURNATEST);
			this.put("X Layer Testnet", EVMChain.XLAYERTEST);
			this.put("X Layer Mainnet", EVMChain.XLAYER);
			this.put("Edgeless Testnet", EVMChain.EDGELESSTEST);
			this.put("B2 Hub Mainnet", EVMChain.B2HUB);
			this.put("B2 Mainnet", EVMChain.B2);
			this.put("Neura Testnet", EVMChain.NEURATEST);
			this.put("Cronos zkEVM Testnet", EVMChain.CRONOSZKTEST);
			this.put("zkCandy Sepolia Testnet", EVMChain.ZKCANDYTEST);
			this.put("Furtheon", EVMChain.FURTHEON);
			this.put("Syndr L3", EVMChain.SYNDR);
			this.put("Boyaa Mainnet", EVMChain.BOYAA);
			this.put("OpTrust Mainnet", EVMChain.OPTRUST);
			this.put("Previewnet", EVMChain.PREVIEWNET);
			this.put("UltronSmartchain", EVMChain.ULTRONSMARTCHAIN);
			this.put("Redstone", EVMChain.REDSTONE);
			this.put("EthXY Testnet", EVMChain.ETHXYTEST);
			this.put("Rebus Mainnet", EVMChain.REBUS);
			this.put("IOTA EVM Testnet", EVMChain.IOTATEST);
			this.put("B2 Hub Testnet", EVMChain.B2HUBTEST);
			this.put("B2 Testnet", EVMChain.B2TEST);
			this.put("Lisk", EVMChain.LISK);
			this.put("ClubMos Mainnet", EVMChain.CLUBMOS);
			this.put("SaitaBlockChain(SBC)", EVMChain.SAITABLOCKCHAIN);
			this.put("Cycle Network Testnet", EVMChain.CYCLETEST);
			this.put("iDos Games Chain Testnet", EVMChain.IDOSTEST);
			this.put("Mint Sepolia Testnet", EVMChain.MINTSEPOLIATEST);
			this.put("UPB CRESCDI Testnet", EVMChain.UPBTEST);
			this.put("AIW3 Testnet", EVMChain.AIW3TEST);
			this.put("NOW Chain", EVMChain.NOW);
			this.put("Adiri", EVMChain.ADIRI);
			this.put("Edgeless Network", EVMChain.EDGELESS);
			this.put("Centrifuge", EVMChain.CENTRIFUGE);
			this.put("Vanar Mainnet", EVMChain.VANAR);
			this.put("Catena Mainnet", EVMChain.CATENA);
			this.put("Oneness TestNet", EVMChain.ONENESSTEST);
			this.put("RSS3 VSL Sepolia Testnet", EVMChain.RSS3TEST);
			this.put("Atleta Olympia", EVMChain.ATLETA);
			this.put("Omnia Chain", EVMChain.OMNIA);
			this.put("Nexis Network Testnet", EVMChain.NEXISTEST);
			this.put("King Of Legends Devnet", EVMChain.KINGTEST);
			this.put("XR Sepolia", EVMChain.XR);
			this.put("Nanon", EVMChain.NANON);
			this.put("Jumbochain Mainnet", EVMChain.JUMBOCHAIN);
			this.put("Morph Holesky", EVMChain.MORPHTEST);
			this.put("Elux Chain", EVMChain.ELUX);
			this.put("Rebus Testnet", EVMChain.REBUSTEST);
			this.put("SatoshiVM Alpha Mainnet", EVMChain.SATOSHIVMALPHATEST);
			this.put("SatoshiVM Testnet", EVMChain.SATOSHIVMTEST);
			this.put("EVOLVE Mainnet", EVMChain.EVOLVE);
			this.put("GAN Testnet", EVMChain.GANTEST);
			this.put("VERY Mainnet", EVMChain.VERY);
			this.put("ONIGIRI Test Subnet", EVMChain.ONIGIRITEST);
			this.put("Nollie Skatechain Testnet", EVMChain.NOLLIETEST);
			this.put("edeXa Mainnet", EVMChain.EDEXA);
			this.put("QIE Blockchain", EVMChain.QIE);
			this.put("Tanssi Demo", EVMChain.TANSSITEST);
			this.put("Tangle", EVMChain.TANGLE);
			this.put("BounceBit Testnet", EVMChain.BOUNCEBITTEST);
			this.put("BounceBit Mainnet", EVMChain.BOUNCEBIT);
			this.put("Aura Euphoria Testnet", EVMChain.AURATEST);
			this.put("Planq Atlas Testnet", EVMChain.PLANQTEST);
			this.put("Cyber Mainnet", EVMChain.CYBER);
			this.put("GDCC TESTNET", EVMChain.GDCCTEST);
			this.put("OpenEX LONG Testnet", EVMChain.OPENEXTEST);
			this.put("Dot Blox", EVMChain.DOTBLOX);
			this.put("Karak Sepolia", EVMChain.KARAKSEPOLIATEST);
			this.put("Shido Testnet Block", EVMChain.SHIDOTEST);
			this.put("Shido Mainnet Block", EVMChain.SHIDO);
			this.put("Ztc Mainnet", EVMChain.ZTC);
			this.put("Tabi Testnet", EVMChain.TABITEST);
			this.put("WorldLand Testnet", EVMChain.WORLDLANDTEST);
			this.put("Shine Chain", EVMChain.SHINE);
			this.put("RSS3 VSL Mainnet", EVMChain.RSS3);
			this.put("Playdapp Testnet", EVMChain.PLAYDAPPTEST);
			this.put("Masa", EVMChain.MASA);
			this.put("Kronobit Mainnet", EVMChain.KRONOBIT);
			this.put("EVOLVE Testnet", EVMChain.EVOLVETEST);
			this.put("Garnet Holesky", EVMChain.GARNETTEST);
			this.put("MXC zkEVM Moonchain", EVMChain.MXC);
			this.put("Titan (TKX)", EVMChain.TITAN);
			this.put("DCpay Mainnet", EVMChain.DCPAY);
			this.put("DreyerX Mainnet", EVMChain.DREYERX);
			this.put("DreyerX Testnet", EVMChain.DREYERXTEST);
			this.put("KLAOS Nova", EVMChain.KLAOS);
			this.put("Nanon Sepolia", EVMChain.NANONTEST);
			this.put("zeroone Mainnet Subnet", EVMChain.ZEROONE);
			this.put("Vizing Testnet", EVMChain.VIZINGTEST);
			this.put("Vizing Mainnet", EVMChain.VIZING);
			this.put("Boba Sepolia", EVMChain.BOBASEPOLIATEST);
			this.put("KaiChain Testnet", EVMChain.KAICHAINTEST);
			this.put("MiYou Mainnet", EVMChain.MIYOU);
			this.put("Zilliqa-2 EVM Devnet", EVMChain.ZILLIQA2TEST);
			this.put("PRM Mainnet", EVMChain.PRM);
			this.put("DODOchain testnet", EVMChain.DODOCHAINTEST);
			this.put("Photon Testnet", EVMChain.PHOTONTEST);
			this.put("Lambda Chain Mainnet", EVMChain.LAMBDA);
			this.put("Testnet Zeroone Subnet", EVMChain.ZEROONETEST);
			this.put("Linea Goerli", EVMChain.LINEATEST);
			this.put("Linea Sepolia", EVMChain.LINEASEPOLIATEST);
			this.put("BOB", EVMChain.BOB);
			this.put("KaiChain", EVMChain.KAICHAIN);
			this.put("OPTOPIA Testnet", EVMChain.OPTOPIATEST);
			this.put("Proof of Play - Apex", EVMChain.PROOF);
			this.put("ICB Testnet", EVMChain.ICBTEST);
			this.put("ICB Network", EVMChain.ICB);
			this.put("BORAchain mainnet", EVMChain.BORACHAIN);
			this.put("ZEDXION", EVMChain.ZEDXION);
			this.put("Unit Zero Testnet", EVMChain.UNIT0TEST);
			this.put("F(x)Core Testnet Network", EVMChain.FXCORETEST);
			this.put("Camp Testnet", EVMChain.CAMPTEST);
			this.put("Odyssey Chain (Testnet)", EVMChain.ODYSSEYTEST);
			this.put("MagApe Testnet", EVMChain.MAGAPETEST);
			this.put("Taiko Hekla L2", EVMChain.TAIKOALPHA7TEST);
			this.put("Bitlayer Mainnet", EVMChain.BITLAYER);
			this.put("HydraDX", EVMChain.HYDRADX);
			this.put("Zillion Sepolia Testnet", EVMChain.ZILLIONTEST);
			this.put("One World Chain Mainnet", EVMChain.ONE);
			this.put("Parex Mainnet", EVMChain.PAREX);
			this.put("AIE Testnet", EVMChain.AIETEST);
			this.put("Playdapp Network", EVMChain.PLAYDAPP);
			this.put("DoCoin Community Chain", EVMChain.DOCOIN);
			this.put("One World Chain Testnet", EVMChain.ONETEST);
			this.put("Eclipse Testnet", EVMChain.ECLIPSECHATEST);
			this.put("Xai Mainnet", EVMChain.XAI);
			this.put("Won Network", EVMChain.WON);
			this.put("zkLink Nova Sepolia Testnet", EVMChain.ZKLINKSEPOLIATEST);
			this.put("PRM Testnet", EVMChain.PRMTEST);
			this.put("REXX Mainnet", EVMChain.REXX);
			this.put("AmChain", EVMChain.AMCHAIN);
			this.put("Netmind Chain Testnet", EVMChain.NETMINDTEST);
			this.put("PlayFi Albireo Testnet", EVMChain.PLAYFITEST);
			this.put("Funki Sepolia Sandbox", EVMChain.FUNKITEST);
			this.put("Moonchain Geneva Testnet", EVMChain.MOONCHAINTEST);
			this.put("COTI Devnet", EVMChain.COTITEST);
			this.put("Lambda Chain Testnet", EVMChain.LAMBDATEST);
			this.put("Kingdom Chain", EVMChain.KINGDOM);
			this.put("Polygon Blackberry", EVMChain.POLYGONBLACKBERRY);
			this.put("Cyber Testnet", EVMChain.CYBERTEST);
			this.put("OP Celestia Raspberry", EVMChain.OPCELESTIARASPBERRY);
			this.put("PTCESCAN Testnet", EVMChain.PTCESCANTEST);
			this.put("PTCESCAN Mainnet", EVMChain.PTCESCAN);
			this.put("RARI Chain Mainnet", EVMChain.RARI);
			this.put("Kakarot Sepolia", EVMChain.KAKAROTTEST);
			this.put("RARI Chain Testnet", EVMChain.RARITEST);
			this.put("Xai Testnet v2", EVMChain.XAITEST2);
			this.put("Arbitrum Blueberry", EVMChain.ARBITRUMBLUEBERRY);
			this.put("DCHAIN Testnet", EVMChain.DCHAINTEST);
			this.put("Mint Mainnet", EVMChain.MINT);
			this.put("UCHAIN Mainnet", EVMChain.UCHAIN);
			this.put("Tobe Chain", EVMChain.TOBE);
			this.put("TAO EVM Testnet", EVMChain.TAOTEST);
			this.put("Xchain Mainnet", EVMChain.XCHAIN);
			this.put("Xchain Testnet", EVMChain.XCHAINTEST);
			this.put("Entangle Mainnet", EVMChain.ENTANGLE);
			this.put("Entangle Testnet", EVMChain.ENTANGLETEST);
			this.put("Etherlink Mainnet", EVMChain.ETHERLINK);
			this.put("Optopia Mainnet", EVMChain.OPTOPIA);
			this.put("PLYR TAU Testnet", EVMChain.PLYRTEST);
			this.put("Inoai Network", EVMChain.INOAI);
			this.put("Chiliz Spicy Testnet", EVMChain.CHILIZTEST);
			this.put("Chiliz Chain Mainnet", EVMChain.CHILIZ);
			this.put("Green Chain Testnet", EVMChain.GREENTEST);
			this.put("Eclat Mainnet", EVMChain.ECLAT);
			this.put("Mind Smart Chain Testnet", EVMChain.MINDSMARTCHAINTEST);
			this.put("Mind Network Testnet", EVMChain.MINDTEST);
			this.put("Eclat Testnet", EVMChain.ECLATTEST);
			this.put("EternalCoin Mainnet", EVMChain.ETERNALCOIN);
			this.put("EthXY", EVMChain.ETHXY);
			this.put("Gravity Alpha Mainnet", EVMChain.GRAVITY);
			this.put("Metal L2 Testnet", EVMChain.METALTEST);
			this.put("Metal L2", EVMChain.METAL);
			this.put("Panarchy", EVMChain.PANARCHY);
			this.put("Aleph Zero Testnet", EVMChain.ALEPHTEST);
			this.put("Sanko", EVMChain.SANKO);
			this.put("Carbonium Testnet Network", EVMChain.CARBONIUMTEST);
			this.put("ONIGIRI Subnet", EVMChain.ONIGIRI);
			this.put("Pools Mainnet", EVMChain.POOLS);
			this.put("Algen", EVMChain.ALGEN);
			this.put("Algen Testnet", EVMChain.ALGENTEST);
			this.put("Algen Layer2", EVMChain.ALGENL2);
			this.put("Algen Layer2 Testnet", EVMChain.ALGENL2TEST);
			this.put("Lycan Chain", EVMChain.LYCAN);
			this.put("Tycooncoin", EVMChain.TYCOONCOIN);
			this.put("L3X Protocol", EVMChain.L3X);
			this.put("L3X Protocol Testnet", EVMChain.L3XTEST);
			this.put("PlayFair Testnet Subnet", EVMChain.PLAYFAIRTEST);
			this.put("Defi Oracle Meta Mainnet", EVMChain.DEFIORACLE);
			this.put("DeFiVerse Mainnet", EVMChain.DEFIVERSE);
			this.put("DeFiVerse Testnet", EVMChain.DEFIVERSETEST);
			this.put("DCpay Testnet", EVMChain.DCPAYTEST);
			this.put("Ebi Chain", EVMChain.EBI);
			this.put("GitAGI Atlas Testnet", EVMChain.GITAGITEST);
			this.put("LAVITA Mainnet", EVMChain.LAVITA);
			this.put("Waterfall 8 Test Network", EVMChain.WATERFALLTEST);
			this.put("ALIENX Hal Testnet", EVMChain.ALIENXTEST);
			this.put("Swan Proxima Testnet", EVMChain.SWANTEST);
			this.put("DCHAIN", EVMChain.DCHAIN);
			this.put("Gravity Alpha Testnet Sepolia", EVMChain.GRAVITYTEST);
			this.put("Poodl Testnet", EVMChain.POODLTEST);
			this.put("ZKBase Sepolia Testnet", EVMChain.ZKBASETEST);
			this.put("Poodl Mainnet", EVMChain.POODL);
			this.put("AgentLayer Testnet", EVMChain.AGENTLAYERTEST);
			this.put("Flag Mainnet", EVMChain.FLAG);
			this.put("Flag Testnet", EVMChain.FLAGTEST);
			this.put("Ramestta Mainnet", EVMChain.RAMESTTA);
			this.put("Pingaksha testnet", EVMChain.PINGAKSHATEST);
			this.put("Settlus Testnet", EVMChain.SETTLUSTEST);
			this.put("XPLA Verse", EVMChain.XPLAVERSE);
			this.put("Sei Network", EVMChain.SEI);
			this.put("Nahmii 3 Mainnet", EVMChain.NAHMII3);
			this.put("Nahmii 3 Testnet", EVMChain.NAHMII3TEST);
			this.put("Nahmii 2 Mainnet", EVMChain.NAHMII2);
			this.put("Aura Mainnet", EVMChain.AURA);
			this.put("Lorenzo", EVMChain.LORENZO);
			this.put("Jiritsu Testnet Subnet", EVMChain.JIRITSUTEST);
			this.put("GEEK Verse Mainnet", EVMChain.GEEK);
			this.put("Taiko Mainnet", EVMChain.TAIKO);
			this.put("BIZ Smart Chain Testnet", EVMChain.BIZTEST);
			this.put("Oraichain Mainnet", EVMChain.ORAICHAIN);
			this.put("Forma", EVMChain.FORMA);
			this.put("Forma Sketchpad", EVMChain.FORMASKETCHPAD);
			this.put("TSC Mainnet", EVMChain.TSC);
			this.put("MAXI Chain Mainnet", EVMChain.MAXI);
			this.put("ITX Mainnet", EVMChain.ITX);
			this.put("NeuroWeb", EVMChain.NEUROWEB);
			this.put("GM Network Mainnet", EVMChain.GMNETWORK);
			this.put("Ham", EVMChain.HAM);
			this.put("ITX Testnet", EVMChain.ITXTEST);
			this.put("MO Mainnet", EVMChain.MO);
			this.put("Space Subnet", EVMChain.SPACE);
			this.put("Hydra Chain Testnet", EVMChain.HYDRATEST);
			this.put("OptimusZ7 Mainnet", EVMChain.OPTIMUSZ7);
			this.put("GLScan", EVMChain.GLSCAN);
			this.put("TAO EVM Mainnet", EVMChain.TAO);
			this.put("LayerEdge testnet", EVMChain.LAYEREDGETEST);
			this.put("Lamina1", EVMChain.LAMINA1);
			this.put("Lamina1 Identity", EVMChain.LAMINA1IDENTITY);
			this.put("Niza Chain Mainnet", EVMChain.NIZA);
			this.put("Niza Chain Testnet", EVMChain.NIZATEST);
			this.put("Space Subnet Testnet", EVMChain.SPACETEST);
			this.put("Zircuit Testnet", EVMChain.ZIRCUITTEST);
			this.put("Citrea Devnet", EVMChain.CITREATEST);
			this.put("GEEK Verse Testnet", EVMChain.GEEKTEST);
			this.put("OptimusZ7 Testnet", EVMChain.OPTIMUSZ7TEST);
			this.put("Form Testnet", EVMChain.FORMTEST);
			this.put("Orange Chain Testnet", EVMChain.ORANGETEST);
			this.put("Atlas", EVMChain.ATLAS);
			this.put("ERAM Mainnet", EVMChain.ERAM);
			this.put("Lamina1 Testnet", EVMChain.LAMINA1TEST);
			this.put("Lamina1 Identity Testnet", EVMChain.LAMINA1IDENTITYTEST);
			this.put("TSC Testnet", EVMChain.TSCTEST);
			this.put("Eternal Mainnet", EVMChain.ETERNAL);
			this.put("Treasure Ruby", EVMChain.TREASURE);
			this.put("MetaLink Network", EVMChain.METALINK);
			this.put("Volley Mainnet", EVMChain.VOLLEY);
			this.put("Cuckoo Sepolia", EVMChain.CUCKOOTEST);
			this.put("Superseed Sepolia Testnet", EVMChain.SUPERSEEDTEST);
			this.put("COINSEC", EVMChain.COINSEC);
			this.put("Xterio Testnet", EVMChain.XTERIOTEST);
			this.put("NumBlock Chain", EVMChain.NUMBLOCK);
			this.put("Fhenix Helium", EVMChain.FHENIX);
			this.put("Nal Sepolia Testnet", EVMChain.NALTEST);
			this.put("GM Network Testnet", EVMChain.GMTEST);
			this.put("Darwinia Koi Testnet", EVMChain.DARWINIATEST);
			this.put("Hybrid Testnet", EVMChain.HYBRIDTEST);
			this.put("Sei Testnet", EVMChain.SEITEST);
			this.put("BigShortBets Testnet", EVMChain.BIGSHORTBETSTEST);
			this.put("iChain Testnet", EVMChain.ICHAINTEST);
			this.put("OX Chain", EVMChain.OX);
			this.put("Vana Satori Testnet", EVMChain.VANATEST);
			this.put("COINSEC Network", EVMChain.COINSEC);
			this.put("Pentagon Testnet", EVMChain.PENTAGONTEST);
			this.put("Open Campus Codex", EVMChain.OPENCAMPUS);
			this.put("Supernet Testnet", EVMChain.SUPERNETTEST);
		}};

		HashMap<String, Boolean> skipnodeurls = new HashMap<String, Boolean>() {{

			this.put("xxxxxxxxxxxxxxxxxxx", true);
			this.put("xxxxxxxxxxxxxxxxxxx", true);
			this.put("http://mainnet.ethstorage.io:9540", true);
			this.put("https://rpc.onenesslabs.io/", true);
			this.put("https://rpc.mainnet.zkamoeba.com/rpc", true);

			this.put("http://127.0.0.1:8545", true); // local
			this.put("https://api.metadium.com/dev", true); // incorrectly added as Metadium mainnet node
			this.put("https://rpc.jolnir.taiko.xyz", true); // old account balance reply but latestblocknr?

			// dns resolve issues, lets not retry
			this.put("https://rpc.chain.namefi.io", true);
			this.put("https://testnet.saharalabs.ai", true);
			this.put("https://rpc_testnet.xfair.ai", true);
			this.put("https://rpc.taiko.xyz", true);
			this.put("https://rpc.dcnetio.cloud", true);
			this.put("https://io-dataseed1.mainnet.edexa.io-market.com/rpc", true);
			this.put("https://rpc-testnet.syndicate.io", true);
			this.put("https://rpc-zkevm.thefirechain.com", true);
			this.put("https://mainnet.evm.nodes.onflow.org", true);
			this.put("https://testnet.evm.nodes.onflow.org", true);
			this.put("https://rpc-mainnet.thefirechain.com", true);
			this.put("https://rpc-mainnet.syndicate.io", true);
			this.put("https://rpc_mainnet.xfair.ai", true);
			this.put("https://rpc_mainnet.mindnetwork.xyz", true);
			this.put("https://coston.enosys.global/ext/C/rpc", true);
			this.put("https://flare.enosys.global/ext/C/rpc", true);
			this.put("https://rinkeby.boba.network/", true);
			this.put("https://rpc.goerli.mudit.blog/", true);
			this.put("https://rpc.pioneer.etm.network", true);
			this.put("https://rpc.soter.one", true);
			this.put("https://kovan.optimism.io/", true);
			this.put("https://testnet-http.dxchain.com", true);
			this.put("https://sokol.poa.network", true);
			this.put("https://rpc.zeeth.io", true);
			this.put("https://mainnet-rpc.dogcoin.me", true);
			this.put("https://rpc.cadaut.com", true);
			this.put("https://rpc-main-1.archiechain.io", true);
			this.put("https://rpc-test-1.archiechain.io", true);
			this.put("https://bobabeam.boba.network", true);
			this.put("https://replica.bobabeam.boba.network", true);
			this.put("https://bobabase.boba.network", true);
			this.put("https://replica.bobabase.boba.network", true);
			this.put("https://rpc.testnet.oychain.io", true);
			this.put("https://rpc.mainnet.oychain.io", true);
			this.put("https://decentralized-web.tech/dw_rpc.php", true);
			this.put("https://mainnet.deamchain.com", true);
			this.put("https://arbitrum.xdaichain.com/", true);
			this.put("https://rpc.latam-blockchain.com", true);
			this.put("https://testnet-rpc.hyperonchain.com", true);
			this.put("https://rpc-bitfalls1.lisinski.online", true);
			this.put("https://rpc-testnet.theconsta.com", true);
			this.put("https://eth-rpc-api-amber.thetatoken.org/rpc", true);
			this.put("https://eth-rpc-api-sapphire.thetatoken.org/rpc", true);
			this.put("https://filecoin-mainnet.chainstacklabs.com/rpc/v1", true);
			this.put("https://replica.bobaopera.boba.network", true);
			this.put("https://bobaopera.boba.network", true);
			this.put("https://rpc.dev.zeeth.io", true);
			this.put("https://dataseed-uk2.beonechain.com", true);
			this.put("https://dataseed-uk1.beonechain.com", true);
			this.put("https://dataseed-us2.beonechain.com", true);
			this.put("https://dataseed-us1.beonechain.com", true);
			this.put("https://dataseed2.beonechain.com", true);
			this.put("https://dataseed1.beonechain.com", true);
			this.put("https://rpc.zkevm.thefirechain.com", true);
			this.put("https://evm-dataseed2.meerscan.com", true);
			this.put("https://evm-dataseed1.meerscan.com", true);
			this.put("https://orig.haichain.io/", true);
			this.put("https://testnet-rpc.aerochain.id/", true);
			this.put("https://eth.plexnode.wtf/", true);
			this.put("https://rpc.qom.one", true);
			this.put("https://rpc-testnet.bcsdev.io", true);
			this.put("https://rpc-mainnet.bcsdev.io", true);
			this.put("https://avastar.cc/ext/bc/C/rpc", true);
			this.put("https://http-testnet.hecochain.com", true);
			this.put("https://rpcurl.plgchain.blockchain.evmnode.online", true);
			this.put("https://beta.evmapi2.nuls.io", true);
			this.put("https://rpc.prodax.io", true);
			this.put("https://beta.evmapi2.nuls.io", true);
			this.put("https://testrpc.bittorrentchain.io/", true);
			this.put("https://rpc.lnscan.org", true);
			this.put("https://rpc.luckynetwork.org", true);
			this.put("https://api.nepalblockchain.dev", true);
			this.put("https://rpc.v3.testnet.pulsechain.com/", true);
			this.put("https://rpc.v2b.testnet.pulsechain.com/", true);
			this.put("https://rpc.v2.testnet.pulsechain.com/", true);
			this.put("https://mainnet-rpc.bitindi.org", true);
			this.put("https://testnet-rpc.bitindi.org", true);
			this.put("https://ngeth.testnet.n3.nahmii.io", true);
			this.put("https://replica.testnet.bobaopera.boba.network", true);
			this.put("https://testnet.bobaopera.boba.network", true);
			this.put("https://rpc-testnet.peperium.io", true);
			this.put("https://api.mainnet.zetachain.com/evm", true);
			this.put("https://evm.klyntar.org/kly_evm_rpc", true);
			this.put("https://evm.klyntarscan.org/kly_evm_rpc", true);
			this.put("https://rpc.x.raba.app/", true);
			this.put("https://hatlas.rpc.hazlor.com:8545", true);
			this.put("https://evm-rpc.teleport.network", true);
			this.put("https://evm-rpc.testnet.teleport.network", true);
			this.put("https://testnet.mdgl.io", true);
			this.put("https://www.krotho-test.net", true);
			this.put("https://testnet-rpc.dogcoin.me", true);
			this.put("https://smartbch.devops.cash/testnet", true);
			this.put("https://smartbch.devops.cash/mainnet", true);
			this.put("https://rpc-mainnet.smartbch.org", true);
			this.put("https://geth.dev.bccloud.net", true);
			this.put("https://rpc2.alvey.io/rpc", true);
			this.put("https://rpc.alveychain.com/rpc", true);
			this.put("https://rpc.senjepowersscan.com", true);
			this.put("https://rpc2.bittexscan.info", true);
			this.put("https://rpc1.bittexscan.info", true);
			this.put("https://dev-rpc.debounce.network", true);
			this.put("https://rpc-testnet.orlchain.com", true);
			this.put("https://api.techpay.io/", true);
			this.put("https://rpc-testnet.hybridchain.ai/", true);
			this.put("https://bombchain-testnet.ankr.com/bas_full_rpc_1", true);
			this.put("https://api.sepolia-deprecated.kroma.network", true);
			this.put("https://rpc.metaplayer.one/", true);
			this.put("https://msc-rpc.movoswap.com", true);
			this.put("https://sparta-rpc.polis.tech", true);
			this.put("https://rpc.polis.tech", true);
			this.put("https://rinkeby.arbitrum.io/rpc", true);
			this.put("https://rpc.kintsugi.themerge.dev", true);
			this.put("https://rpc.kiln.themerge.dev", true);
			this.put("https://rpc.zhejiang.ethpandaops.io", true);
			this.put("https://devnetopenapi2.platon.network/rpc", true);
			this.put("https://worlds-test.calderachain.xyz/http", true);
			this.put("https://tx.aquacha.in/api", true);
			this.put("https://toys.joys.cash/", true);
			this.put("https://londonpublic.alphabetnetwork.org", true);
			this.put("https://main-rpc.com", true);
			this.put("https://molereum.jdubedition.com", true);
			this.put("https://alpha-1-replica-0.bedrock-goerli.optimism.io", true);
			this.put("https://alpha-1-replica-1.bedrock-goerli.optimism.io", true);
			this.put("https://alpha-1-replica-2.bedrock-goerli.optimism.io", true);
			this.put("https://testrpc.opside.network", true);
			this.put("https://mainnet-rpc.memescan.io", true);
			this.put("https://mainnet-rpc2.memescan.io", true);
			this.put("https://mainnet-rpc3.memescan.io", true);
			this.put("https://mainnet-rpc4.memescan.io", true);
			this.put("https://rpc.ssquad.games", true);
			this.put("https://node.0xtchain.com", true);
			this.put("https://testnet-web3.wolot.io", true);
			this.put("https://testnet.buildwithtoki.com/v0/rpc", true);
			this.put("https://mainnet.buildwithtoki.com/v0/rpc", true);
			this.put("https://l2.testnet.nahmii.io", true);
			this.put("https://replica.testnet.avax.boba.network", true);
			this.put("https://testnet.avax.boba.network", true);
			this.put("nodeURL https://ukrpc.doken.dev", true);
			this.put("https://mainnet.aerielab.io", true);
			this.put("https://rpc.beverlyhills.ethdevops.io:8545", true);
			this.put("https://triton.api.nautchain.xyz", true);
			this.put("https://evm.cryptocurrencydevs.org", true);
			this.put("https://rpc.brochain.org", true);
			this.put("http://rpc.brochain.org", true);
			this.put("https://rpc.brochain.org/mainnet", true);
			this.put("http://rpc.brochain.org/mainnet", true);
			this.put("https://remote.akroma.io", true);
			this.put("https://chain-rpc.mythicalgames.com", true);
			this.put("https://godwoken-testnet-web3-v1-rpc.ckbapp.dev", true);
			this.put("https://api.s3.t.hmny.io", true);
			this.put("https://api.s2.t.hmny.io", true);
			this.put("https://churchill-rpc.pepchain.io", true);
			this.put("https://mewapi.musicoin.tw", true);
			this.put("https://mainnet-external.openvessel.io", true);
			this.put("https://api.s0.t.posichain.org", true);
			this.put("https://api.s1.d.posichain.org", true);
			this.put("https://testnet1.haymo.network", true);
			this.put("https://testnet.hashkeychain/rpc", true);
			this.put("https://rpc1.conet.network", true);
			this.put("https://rpc.condrieu.ethdevops.io:8545", true);
			this.put("https://godwoken-testnet-web3-rpc.ckbapp.dev", true);
			this.put("https://avax.boba.network", true);
			this.put("https://replica.avax.boba.network", true);
			this.put("https://rpc-02.frenscan.io", true);
			this.put("https://sgrpc.doken.dev", true);
			this.put("https://nyrpc.doken.dev", true);
			this.put("https://api.s0.d.posichain.org", true);

			// ssl errors, timeouts, ..
			this.put("https://rethereum.rpc.restratagem.com", true);
			this.put("https://host-76-74-29-34.contentfabric.io/eth/", true);
			this.put("https://host-60-240-133-202.contentfabric.io/eth/", true);
			this.put("https://quartz.api.onfinality.io/public-ws", true);
			this.put("https://node3.fibo-api.asia", true);
			this.put("https://node4.fibo-api.asia", true);
			this.put("https://node5.fibo-api.asia", true);
			this.put("https://node6.fibo-api.asia", true);
			this.put("https://node7.fibo-api.asia", true);
			this.put("https://liberty20.shardeum.org/", true);
			this.put("https://liberty10.shardeum.org/", true);
			this.put("https://canto.dexvaults.com/", true);
			this.put("https://canto.neobase.one", true);
			this.put("https://kava-evm.rpc.thirdweb.com", true);
			this.put("https://kava-evm-testnet.rpc.thirdweb.com", true);
			this.put("https://rpc.ankr.com/dogechain", true);
			this.put("https://matic-mainnet-full-rpc.bwarelabs.com", true);
			this.put("https://matic-mainnet.chainstacklabs.com", true);
			this.put("https://rpc-mainnet.matic.network", true);
			this.put("https://web3endpoints.com/gnosischain-mainnet", true);
			this.put("https://api.mycryptoapi.com/eth", true);
			this.put("https://rpc.thaichain.org", true);
			this.put("https://staging.diode.io:8443/", true);
			this.put("https://rpc.thaifi.com", true);
			this.put("https://sgb.lightft.so/rpc", true);
			this.put("https://sgb-rpc.ftso.eu", true);
			this.put("https://testrpc.genesisl1.org", true);
			this.put("https://test2.goodata.io", true);
			this.put("https://rpc.goodata.io", true);
			this.put("https://rpc.tbwg.io", true);
			this.put("https://mainnet.dxchain.com", true);
			this.put("https://rpc.valorbit.com/v2", true);
			this.put("https://pangoro-rpc.darwinia.network", true);
			this.put("https://mainnet.openpiece.io", true);
			this.put("http://test-rpc.dbmbp.com", true);
			this.put("https://http-mainnet2.hoosmartchain.com", true);
			this.put("https://rpc2.mix-blockchain.org:8647", true);
			this.put("https://rpc.genechain.io", true);
			this.put("https://linqto-dev.com", true);
			this.put("https://testnet.gatenode.cc", true);
			this.put("https://0x57.redjackstudio.com", true);
			this.put("https://rpc.novanetwork.io:9070", true);
			this.put("https://rpc-3.zyx.network/", true);
			this.put("https://api.eosargentina.io", true);
			this.put("https://okc-mainnet.gateway.pokt.network/v1/lb/6275309bea1b320039c893ff", true);
			this.put("https://s0.garizon.net/rpc", true);
			this.put("https://s1.garizon.net/rpc", true);
			this.put("https://rpc-3.zyx.network/", true);
			this.put("https://jsonrpc.ellaism.org", true);
			this.put("https://s0.garizon.net/rpc", true);
			this.put("https://s1.garizon.net/rpc", true);
			this.put("https://s2.garizon.net/rpc", true);
			this.put("https://s3.garizon.net/rpc", true);
			this.put("https://rpc1.camdl.gov.kh/", true);
			this.put("https://core.poa.network", true);
			this.put("https://api.einc.io/jsonrpc/mainnet", true);
			this.put("https://testnet-rpc-0.web3games.org/evm", true);
			this.put("https://testnet-rpc-1.web3games.org/evm", true);
			this.put("https://testnet-rpc-2.web3games.org/evm", true);
			this.put("https://klc.live/", true);
			this.put("https://devnet.web3games.org/evm", true);
			this.put("https://testnet.rpc.novanetwork.io", true);
			this.put("https://protontestnet.greymass.com/", true);
			this.put("https://testnet.ten.xyz", true);
			this.put("https://sepolia.synapseprotocol.com", true);
			this.put("https://mainnet.rpc1.thefirechain.com", true);
			this.put("https://candle-rpc.com/", true);
			this.put("https://pawchainx.com/", true);
			this.put("https://rpc.velaverse.io", true);
			this.put("https://rpc.testnet.tao.network", true);
			this.put("http://rpc.testnet.tao.network:8545", true);
			this.put("https://rpc.tao.network", true);
			this.put("https://rpc.astar.network:8545", true);
			this.put("https://mathchain-asia.maiziqianbao.net/rpc", true);
			this.put("https://s2.tl.web.tr:4041", true);
			this.put("https://seed5.evanesco.org:8547", true);
			this.put("https://dataseed.popcateum.org", true);
			this.put("https://tapi.entercoin.net/", true);
			this.put("https://nodes.halo.land", true);
			this.put("https://mainnet.exzo.technology", true);
			this.put("https://rpc.api.moonrock.moonbeam.network", true);
			this.put("https://test.doschain.com/jsonrpc", true);
			this.put("https://mainnet.zakumi.io", true);
			this.put("https://rpc-api.kalarchain.tech", true);
			this.put("https://mainnet.sherpax.io/rpc", true);
			this.put("https://sherpax-testnet.chainx.org/rpc", true);
			this.put("https://beagle.chat/eth", true);
			this.put("https://send.catechain.com", true);
			this.put("https://rpc.atheios.org/", true);
			this.put("https://dataseed1.btachain.com/", true);
			this.put("https://geth.anytype.io", true);
			this.put("https://tea.mining4people.com/rpc", true);
			this.put("http://172.104.194.36:8545", true);
			this.put("https://rabbit.analog-rpc.com", true);
			this.put("https://http-mainnet-sg.cube.network", true);
			this.put("https://http-mainnet-us.cube.network", true);
			this.put("https://http-testnet.cube.network", true);
			this.put("https://mainnet-data.rubychain.io/", true);
			this.put("https://mainnet.rubychain.io/", true);
			this.put("https://tsfapi.europool.me", true);
			this.put("https://rpc.cartenz.works", true);
			this.put("http://rpc.boyanet.org:8545", true);
			this.put("https://rpc.sportschainnetwork.xyz/", true);
			this.put("https://mainnet.d-chain.network/ext/bc/2ZiR1Bro5E59siVuwdNuRFzqL95NkvkbzyLBdrsYR9BLSHV7H4/rpc", true);
			this.put("https://rpc.dexilla.com", true);
			this.put("https://rpc.metatime.com/eleanor", true);
			this.put("https://rpc.scschain.com", true);
			this.put("https://testnet.eurus.network", true);
			this.put("http://rpc.satosh.ie", true);
			this.put("http://testnet.satosh.ie", true);
			this.put("https://rpc.dev.publicmint.io:8545", true);
			this.put("https://api.ecoball.org/espuma/", true);
			this.put("https://market.bigsb.io", true);
			this.put("https://rpc.public-2138.defi-oracle.io", true);
			this.put("https://dsc-rpc.digitsoul.co.th", true);
			this.put("https://peerpay.su.gy/p2p", true);
			this.put("https://testnet-rpc.scolcoin.com", true);
			this.put("https://rpc-testnet-v1.foxchain.app/", true);
			this.put("https://testnet.arcology.network/rpc", true);
			this.put("https://gnosischain-rpc.gateway.pokt.network", true);
			this.put("https://rpc.etherlite.org", true);
			this.put("https://connect.dehvo.com", true);
			this.put("https://rpc.dehvo.com", true);
			this.put("https://rpc1.dehvo.com", true);
			this.put("https://rpc2.dehvo.com", true);
			this.put("https://rcl-dataseed1.rclsidechain.com", true);
			this.put("https://rcl-dataseed2.rclsidechain.com", true);
			this.put("https://rcl-dataseed3.rclsidechain.com", true);
			this.put("https://rcl-dataseed4.rclsidechain.com", true);
			this.put("https://testnet.openpiece.io", true);
			this.put("https://mainnet.deamchain.com", true);
			this.put("https://testnet-rpc.oeblock.com", true);
			this.put("https://evascan.io/api/eth-rpc/", true);
			this.put("https://node.sirius.lightstreams.io", true);
			this.put("https://node.mainnet.lightstreams.io", true);
			this.put("https://testnet.omni.network", true);
			this.put("https://node.atoshi.io/", true);
			this.put("https://http-testnet.hoosmartchain.com", true);
			this.put("https://rpc.public-0138.defi-oracle.io", true);
			this.put("https://testnet-rpc.neutrinoschain.com", true);
			this.put("https://gateway.moac.io/testnet", true);
			this.put("https://mainnet.structx.io", true);
			this.put("http://13.57.207.168:3435", true);
			this.put("https://mainnet.shinarium.org", true);
			this.put("https://rpc.swapdex.network", true);
			this.put("https://rpcurl.mainnet.plgchain.com", true);
			this.put("https://sur.nilin.org", true);
			this.put("https://public-rpc.blockpi.io/http/kcc", true);
			this.put("https://mainnet.web3q.io:8545", true);
			this.put("https://rpc.pepe-chain.vip", true);
			this.put("https://arrakis.gorengine.com/own", true);
			this.put("https://rpc.juncachain.com", true);
			this.put("https://rpc-testnet.juncachain.com", true);
			this.put("https://rest.furya.io", true);
			this.put("https://rpc.lycanchain.com/", true);
			this.put("https://node-testnet.vention.network", true);
			this.put("https://node.cheapeth.org/rpc", true);
			this.put("https://subnets.avax.network/portal-fantasy/testnet/rpc", true);
			this.put("https://rpc.woowow.io", true);
			this.put("https://rpc.main.oasvrs.bnken.net", true);
			this.put("https://api.ambros.network", true);
			this.put("https://s0-testnet.garizon.net/rpc", true);
			this.put("https://s1-testnet.garizon.net/rpc", true);
			this.put("https://s2-testnet.garizon.net/rpc", true);
			this.put("https://geth-mordor.etc-network.info", true);
			this.put("https://testnet.evascan.io/api/eth-rpc/", true);
			this.put("https://blockchain-api-mainnet.permission.io/rpc", true);
			this.put("https://rpcurl.mainnet.plgchain.plinga.technology", true);
			this.put("https://kcc.mytokenpocket.vip", true);
			this.put("https://dxt.dexit.network", true);
			this.put("https://s3-testnet.garizon.net/rpc", true);
			this.put("https://layer1test.decentrabone.com", true);
			this.put("https://api.nepalblockchain.network", true);
			this.put("https://rpc.gton.network/", true);
			this.put("https://mainnet.eurus.network/", true);
			this.put("http://128.199.94.183:8041", true);
			this.put("https://evm-testnet.bronos.org", true);
			this.put("https://evm.humans.stakepool.dev.br", true);
			this.put("https://evm-rpc.mainnet.humans.zone", true);
			this.put("https://mathchain-us.maiziqianbao.net/rpc", true);
			this.put("https://galois-hk.maiziqianbao.net/rpc", true);
			this.put("https://dataseed.iorachain.com", true);
			this.put("https://testapi.cicscan.com", true);
			this.put("https://http-testnet-sg.cube.network", true);
			this.put("https://http-testnet-jp.cube.network", true);
			this.put("https://http-testnet-us.cube.network", true);
			this.put("https://rpc.tst.publicmint.io:8545", true);
			this.put("https://rpc.qkacoin.org", true);
			this.put("https://api.ecoball.org/ecoball/", true);
			this.put("https://prod-forge.prod.findora.org:8545/", true);
			this.put("https://rpc.antofy.io", true);
			this.put("https://bc.vcex.xyz", true);
			this.put("https://rpc.bombchain.com", true);
			this.put("https://coredata-mainnet.hybridchain.ai/", true);
			this.put("https://rpc-mainnet.hybridchain.ai", true);
			this.put("https://api.ezchain.com/ext/bc/C/rpc", true);
			this.put("https://testnet-api.ezchain.com/ext/bc/C/rpc", true);
			this.put("https://rpc.btxtestchain.com", true);
			this.put("https://dimension-rpc.xpla.dev", true);
			this.put("https://rpc.zkevm.ghostrider.thefirechain.com", true);
			this.put("https://www.dracscan.com/rpc", true);
			this.put("https://api.dynoprotocol.com", true);
			this.put("https://tapi.dynoprotocol.com", true);
			this.put("https://data-mainnet-v1.somanetwork.io/", true);
			this.put("https://id-mainnet.somanetwork.io", true);
			this.put("https://hk-mainnet.somanetwork.io", true);
			this.put("https://sg-mainnet.somanetwork.io", true);
			this.put("https://evm-rpc.testnet.humans.zone", true);
			this.put("https://rpc1.phi.network", true);
			this.put("https://rpc2.phi.network", true);
			this.put("https://rpc.chain.nexi.technology/", true);
			this.put("https://chain.nexilix.com", true);
			this.put("https://chain.nexi.evmnode.online", true);
			this.put("https://janus.htmlcoin.com/api/", true);
			this.put("https://rpc-evm-testnet.venidium.io", true);
			this.put("https://test-taycan.hupayx.io", true);
			this.put("https://babel-api.mainnet.iotex.io", true);
			this.put("https://rpc.meversetestnet.io", true);
			this.put("https://mainnet-rpc.tlxscan.com/", true);
			this.put("https://network.uzmigames.com.br/", true);
			this.put("https://nodetestnet-station-one.tritanium.network/", true);
			this.put("https://nodetestnet-station-two.tritanium.network/", true);
			this.put("http://185.99.196.3:8545", true);
			this.put("https://127.0.0.1:7545", true);
			this.put("https://node-api.alp.uptn.io/v1/ext/rpc", true);
			this.put("https://rpc2-testnet-v1.foxchain.app/", true);
			this.put("https://rpc-athena.ardescan.com/", true);
			this.put("https://rpc.biteth.org", true);
			this.put("https://rpc.e-dollar.org", true);
			this.put("https://pre-boc1.beonechain.com", true);
			this.put("https://rpc.blocktonscan.com/", true);
			this.put("https://api.dracones.net/", true);
			this.put("https://mainnet-web3.wolot.io", true);
			this.put("https://mainnet.berylbit.io", true);
			this.put("https://qeasyweb3.com", true);
			this.put("https://genesis-gn.com", true);
			this.put("https://rpc-mainnet.pepenetwork.io", true);
			this.put("https://data-aws-testnet.imperiumchain.com", true);
			this.put("https://data-aws2-testnet.imperiumchain.co", true);
			this.put("https://data-aws-mainnet.imperiumchain.com", true);
			this.put("https://data-aws2-mainnet.imperiumchain.com", true);
			this.put("https://rpc-testnet.smartbch.org", true);
			this.put("http://geth.free.idcfengye.com", true);
			this.put("https://eu.mainnet.xixoio.com", true);
			this.put("https://us.mainnet.xixoio.com", true);
			this.put("https://asia.mainnet.xixoio.com", true);
			this.put("http://node106.cryptocoinpay.info:8545", true);
			this.put("https://rpc.astranaut.io", true);
			this.put("https://rpc1.astranaut.io", true);
			this.put("https://rpc.astranaut.dev", true);
			this.put("https://mainnet-rpc.satoshichain.io", true);
			this.put("https://zerorpc.singularity.gold", true);
			this.put("https://node4.fibo-rpc.asia", true);
			this.put("https://node5.fibo-rpc.asia", true);
			this.put("https://node6.fibo-rpc.asia", true);
			this.put("https://node7.fibo-rpc.asia", true);
			this.put("https://testnet-rpc.rikscan.com", true);
			this.put("https://testnet-rpc.quantumscan.org", true);
			this.put("https://gateway.opn.network/node/ext/bc/2VsZe5DstWw2bfgdx3YbjKcMsJnNDjni95sZorBEdk9L9Qr9Fr/rpc", true);
			this.put("https://www.3sps.net", true);
			this.put("https://api.testnet-dev.trust.one", true);
			this.put("https://mainnet.metadot.network", true);
			this.put("https://testnet.metadot.network", true);
			this.put("https://rpc.fod.games/", true);
			this.put("https://seed.btcix.org/rpc", true);
			this.put("https://taycan-rpc.hupayx.io:8545", true);
			this.put("https://testnet-rpc.antofy.io", true);
			this.put("http://testnet-rpc.blastblockchain.com", true);
			this.put("http://testnet.dev.svcs.ferrumnetwork.io:9933", true);
			this.put("http://testnet.dev.svcs.ferrumnetwork.io:9933", true);
			this.put("https://mainnet-rpc.hertzscan.com", true);
			this.put("https://api.esn.gonspool.com", true);
			this.put("https://testnet-rpc.gochain.io", true);
			this.put("https://ava.network:21015/ext/evm/rpc", true);
			this.put("https://testnet.neonevm.org", true);
			this.put("https://testnet.gather.network", true);
			this.put("https://rpc.iposlab.com", true);
			this.put("https://mainnet.ipdc.io/", true);
			this.put("https://smart.zeniq.network:9545", true);
			this.put("https://wallrpc.pirl.io", true);
			this.put("https://23.92.21.121:8545", true);
			this.put("https://rpc2.iposlab.com", true);
			this.put("https://devnet.gather.network", true);
			this.put("https://flachain.flaexchange.top/", true);
			this.put("https://node.joys.digital", true);
			this.put("https://net.iolite.io", true);
			this.put("https://mainnet-rpc.soverun.com", true);
			this.put("https://api.electroneum.com", true);
			this.put("http://rpc.testnet.debank.com", true);
			this.put("https://rpc.xerom.org", true);
			this.put("https://chain.deptofgood.com", true);
			this.put("https://mainnet-rpc.curvescan.io", true);
			this.put("https://weelinknode1c.gw002.oneitfarm.com", true);
			this.put("https://l2-testnet-rpc.altscan.org", true);
			this.put("https://filecoin-calibration.chainstacklabs.com/rpc/v1", true);
			this.put("https://jellie-rpc.twala.io/", true);
			this.put("https://devnetopenapi.alaya.network/rpc", true);
			this.put("https://testnet.condor.systems/rpc", true);
			this.put("https://rpc.l3test.taiko.xyz", true);
			this.put("https://rpc.test.taiko.xyz", true);
			this.put("https://rpcmainnet.ic-plaza.org/", true);
			this.put("https://rpc2.metachain.one", true);
			this.put("http://eth-jrpc.devnet.quarkchain.io:39907", true);
			this.put("https://devnet-s1-ethapi.quarkchain.io", true);
			this.put("http://eth-jrpc.devnet.quarkchain.io:39901", true);
			this.put("https://devnet-s3-ethapi.quarkchain.io", true);
			this.put("https://testnet-rpc.soverun.com", true);
			this.put("http://jrpc.mainnet.quarkchain.io:38391", true);
			this.put("https://testnet.rpc.uschain.network", true);
			this.put("https://testnet-rpc.eliberty.ngo", true);
			this.put("https://scoville-rpc.chiliz.com", true);
			this.put("http://testnet.cybertrust.space:48501", true);
			this.put("https://rpc.quantumscan.org", true);
			this.put("http://toronet.org/rpc", true);
			this.put("https://mainnet-rpc.vention.network", true);
			this.put("http://testnet.cosmicchain.site:3344", true);
			this.put("https://aium-rpc-dev.viacube.com", true);
			this.put("https://test103.thinkiumrpc.net/", true);
			this.put("https://test1.thinkiumrpc.net/", true);
			this.put("https://test2.thinkiumrpc.net/", true);
			this.put("https://api.electroneum.com", true);
			this.put("https://testnet.gton.network/", true);
			this.put("https://rpc.autobahn.network", true);
			this.put("https://rpc.blgchain.com", true);
			this.put("https://testnet-rpc0.piecenetwork.com", true);
			this.put("https://rpc.blgchain.com", true);
			this.put("https://betaenv.singularity.gold:18545", true);
			this.put("https://rpc-test.arthera.net", true);
			this.put("https://data-aws2-testnet.imperiumchain.com", true);
			this.put("https://testnet.neonlink.io", true);
			this.put("https://u0ma6t6heb:KDNwOsRDGcyM2Oeui1p431Bteb4rvcWkuPgQNHwB4FM@u0xy4x6x82-u0e2mg517m-rpc.us0-aws.kaleido.io/", true);
			this.put("https://rpc3-testnet-v1.foxchain.app", true);
			this.put("https://rpc.main.smartlayer.network", true);
			this.put("https://mainnet.bmcchain.com/", true);
			this.put("https://rpc.moonsama.com", true);
			this.put("https://node0.testnet.treasurenet.io", true);
			this.put("https://node1.testnet.treasurenet.io", true);
			this.put("https://node2.testnet.treasurenet.io", true);
			this.put("https://node3.testnet.treasurenet.io", true);
			this.put("https://main.doschain.com.", true);
			this.put("https://rpc.oracle.liveplex.io", true);
			this.put("http://testnet.toronet.org/rpc", true);
			this.put("https://test.thinkiumrpc.net/", true);
			this.put("https://ukrpc.doken.dev", true);
			this.put("https://u0tnafcv6j:o2T045sxuCNXL878RDQLp5__Zj-es2cvdjtgkl4etn0@u0v7kwtvtg-u0wj114sve-rpc.us0-aws.kaleido.io/", true);
			this.put("https://rpc.condrieu.ethdevops.io:8545", true);
			this.put("https://proxy.thinkiumrpc.net/", true);
			this.put("https://testnet-rpc.foundryscan.org/", true);
			this.put("http://jrpc.devnet.quarkchain.io:38391", true);
			this.put("https://devnet-s0-ethapi.quarkchain.io", true);
			this.put("https://devnet-s0-ethapi.quarkchain.io", true);
			this.put("http://eth-jrpc.devnet.quarkchain.io:39900", true);
			this.put("https://devnet-s2-ethapi.quarkchain.io", true);
			this.put("http://eth-jrpc.devnet.quarkchain.io:39902", true);
			this.put("https://devnet-s3-ethapi.quarkchain.io", true);
			this.put("http://eth-jrpc.devnet.quarkchain.io:39904", true);
			this.put("http://eth-jrpc.devnet.quarkchain.io:39905", true);
			this.put("https://mainnet.bmcchain.com/", true);
			this.put("https://rpc.moonsama.com", true);
			this.put("https://node0.testnet.treasurenet.io", true);
			this.put("https://node1.testnet.treasurenet.io", true);
			this.put("https://node2.testnet.treasurenet.io", true);
			this.put("https://node3.testnet.treasurenet.io", true);
			this.put("https://main.doschain.com", true);
			this.put("https://rpc.oracle.liveplex.io", true);
			this.put("http://testnet.toronet.org/rpc", true);
			this.put("https://test.thinkiumrpc.net/", true);
			this.put("https://ukrpc.doken.dev", true);
			this.put("https://u0tnafcv6j:o2T045sxuCNXL878RDQLp5__Zj-es2cvdjtgkl4etn0@u0v7kwtvtg-u0wj114sve-rpc.us0-aws.kaleido.io/", true);
			this.put("https://proxy.thinkiumrpc.net/", true);
			this.put("https://godwoken-testnet-web3-rpc.ckbapp.dev", true);
			this.put("https://testnet-rpc.foundryscan.org/", true);
			this.put("http://jrpc.devnet.quarkchain.io:38391", true);
			this.put("https://devnet-s0-ethapi.quarkchain.io", true);
			this.put("http://eth-jrpc.devnet.quarkchain.io:39900", true);
			this.put("https://devnet-s2-ethapi.quarkchain.io", true);
			this.put("http://eth-jrpc.devnet.quarkchain.io:39902", true);
			this.put("https://devnet-s3-ethapi.quarkchain.io", true);
			this.put("https://devnet-s4-ethapi.quarkchain.io", true);
			this.put("http://eth-jrpc.devnet.quarkchain.io:39904", true);
			this.put("http://eth-jrpc.devnet.quarkchain.io:39905", true);
			this.put("http://eth-jrpc.devnet.quarkchain.io:39906", true);
			this.put("https://rpc.node1.etnd.pro/", true);
			this.put("https://mainnet.tafchain.com/v1", true);
			this.put("https://socialsmartchain.digitalnext.business", true);
			this.put("https://testnet.bitfinity.network", true);
			this.put("https://mainnet.kekchain.com", true);
			this.put("https://testnet.kekchain.com", true);
			this.put("https://rpc.testnet.fastexchain.com", true);
			this.put("https://baas-rpc.luniverse.io:18545?lChainId=1641349324562974539", true);
			this.put("https://rpc.shinarium.org", true);
			this.put("https://mainnet-rpc.bescscan.io", true);
			this.put("https://brnkc-test.bearnetwork.net", true);
			this.put("https://host-76-74-28-226.contentfabric.io/eth/", true);
			this.put("https://devchain-poa.huabeizhenxuan.com", true);
			this.put("https://jsonrpc-test.imversed.network", true);
			this.put("https://ws-jsonrpc-test.imversed.network", true);
			this.put("https://mainnet.hokum.gg", true);
			this.put("https://testnet-rpc.exlscan.co", true);
			this.put("https://rpc.auxilium.global", true);
			this.put("http://174.138.9.169:9650/ext/bc/VUKSzFZKckx4PoZF9gX5QAqLPxbLzvu1vcssPG5QuodaJtdHT/rpc", true);
			this.put("https://harmony.api.onfinality.io/public", true);
			this.put("https://rpc-mainnet.lachain.io", true);
			this.put("https://devnet-s5-ethapi.quarkchain.io", true);
			this.put("https://devnet-s6-ethapi.quarkchain.io", true);
			this.put("https://devnet-s7-ethapi.quarkchain.io", true);
			this.put("https://node.ghostnet.etherlink.com", true);
			this.put("https://ws-jsonrpc.imversed.network", true);
			this.put("https://jp.rpc.qkiscan.io", true);
			this.put("https://testnet.hokum.gg", true);
			this.put("https://testnet-rpc.exlscan.com", true);
			this.put("https://rpc.exlscan.com", true);
			this.put("xxxxxxxx", true);
			this.put("xxxxxxxx", true);
			this.put("xxxxxxxx", true);
			this.put("xxxxxxxx", true);
			this.put("xxxxxxxx", true);
			this.put("xxxxxxxx", true);
			this.put("xxxxxxxx", true);
			this.put("xxxxxxxx", true);
			this.put("xxxxxxxx", true);
			this.put("xxxxxxxx", true);
			this.put("xxxxxxxx", true);
		}};

		HashMap<String, Boolean> skipchains = new HashMap<String, Boolean>() {{

			// messy
			this.put("Hybrid Testnet (Deprecated)", true);
			this.put("Santiment Intelligence Network", true);

			// multinode
			this.put("Songbird Canary-Network", true);
			this.put("Crab Network", true);
			this.put("Darwinia Network", true);
			this.put("Zyx Mainnet", true);
			this.put("Decimal Smart Chain Mainnet", true);
			this.put("Zenith Mainnet", true);
			this.put("Velas EVM Mainnet", true);
			this.put("ThunderCore Mainnet", true);
			this.put("ENULS Mainnet", true);
			this.put("Engram Testnet", true);
			this.put("X1 Testnet", true);
			this.put("Bitnet", true);
			this.put("LaChain", true);
			this.put("Orderly Mainnet", true);
			this.put("Neurochain Mainnet", true);
			this.put("Shiden", true);
			this.put("LaTestnet", true);
			this.put("Optimism Goerli Testnet", true);
			this.put("Areon Network Testnet", true);
			this.put("Areon Network Mainnet", true);
			this.put("XT Smart Chain Mainnet", true);
			this.put("MAAL Chain", true);
			this.put("Qitmeer", true);
			this.put("Fantasia Chain Mainnet", true);
			this.put("Humans.ai Mainnet", true);
			this.put("DeFiMetaChain Changi Testnet", true);
			this.put("AIA Mainnet", true);
			this.put("BEVM Canary", true);
			this.put("Horizen Gobi Testnet", true);
			this.put("edeXa Testnet", true);
			this.put("MainnetZ Mainnet", true);
			this.put("Movo Smart Chain Mainnet", true);
			this.put("BOSagora Mainnet", true);
			this.put("Krest Network", true);
			this.put("XODEX", true);
			this.put("Tangle Testnet", true);
			this.put("Nexi V2 Mainnet", true);
			this.put("BlackFort Exchange Network", true);
			this.put("Treasurenet Mainnet Alpha", true);
			this.put("Bahamut", true);
			this.put("EraSwap Mainnet", true);
			this.put("Wegochain Rubidium Mainnet", true);
			this.put("Tres Mainnet", true);
			this.put("IRIShub", true);
			this.put("Compverse Mainnet", true);
			this.put("PolySmartChain", true);
			this.put("Bitrock Mainnet", true);
			this.put("Horizen EON Mainnet", true);
			this.put("MaalChain Testnet", true);
			this.put("Qitmeer Network Testnet", true);
			this.put("Opal testnet by Unique", true);
			this.put("Sapphire by Unique", true);
			this.put("Mammoth Mainnet", true);
			this.put("JIBCHAIN L1", true);
			this.put("Boba BNB Testnet", true);
			this.put("Smart Bitcoin Cash", true);
			this.put("Gon Chain", true);
			this.put("Gnosis Chiado Testnet", true);
			this.put("MaxxChain Mainnet", true);
			this.put("HashBit Mainnet", true);
			this.put("Haqq Network", true);
			this.put("Arbitrum Nova", true);
			this.put("Wireshape Floripa Testnet", true);
			this.put("Lumoz Testnet Alpha", true);
			this.put("Etica Mainnet", true);
			this.put("MultiVAC Mainnet", true);
			this.put("GuapcoinX", true);
			this.put("Godwoken Testnet v1", true);
			this.put("Dragonfly Mainnet (Hexapod)", true);
			this.put("Mantis Testnet (Hexapod)", true);
			this.put("QuarkChain Mainnet Shard 0", true);
			this.put("QuarkChain Mainnet Shard 1", true);
			this.put("QuarkChain Mainnet Shard 2", true);
			this.put("QuarkChain Mainnet Shard 3", true);
			this.put("QuarkChain Mainnet Shard 4", true);
			this.put("QuarkChain Mainnet Shard 5", true);
			this.put("QuarkChain Mainnet Shard 6", true);
			this.put("QuarkChain Mainnet Shard 7", true);
			this.put("Bear Network Chain Mainnet", true);
			this.put("Posichain Mainnet Shard 0", true);
			this.put("quarkblockchain", true);
			this.put("Pego Network", true);
			this.put("Harmony Mainnet Shard 0", true);

			// add?
			this.put("Fuse Mainnet", true);
			this.put("Fuse Sparknet", true);
			this.put("Rollux Mainnet", true);
			this.put("Blast Mainnet", true);
			this.put("Oasys Mainnet", true);
			this.put("zkSync Mainnet", true);
			this.put("Klaytn Testnet Baobab", true);
			this.put("X1 Devnet", true);
			this.put("X1 Network", true);
			this.put("EOS EVM Network", true);
			this.put("EOS EVM Network Testnet", true);
			this.put("Beam Testnet", true);
			this.put("Immutable zkEVM", true);

			// single node
			this.put("All About Healthy", true); // scam
			this.put("Expanse Network", true);
			this.put("ThaiChain", true);
			this.put("Diode Prenet", true);
			this.put("ThunderCore Testnet", true);
			this.put("Elastos Smart Chain", true);
			this.put("Elastos Smart Chain Testnet", true);
			this.put("Genesis L1", true);
			this.put("SecureChain Mainnet", true);
			this.put("U2U Solaris Mainnet", true);
			this.put("Darwinia Pangolin Testnet", true);
			this.put("Acria IntelliChain", true);
			this.put("Ennothem Mainnet Proterozoic", true);
			this.put("CoinEx Smart Chain Mainnet", true);
			this.put("CoinEx Smart Chain Testnet", true);
			this.put("GoChain", true);
			this.put("Hoo Smart Chain", true);
			this.put("IDChain Mainnet", true);
			this.put("PrimusChain mainnet", true);
			this.put("Meter Mainnet", true);
			this.put("Meter Testnet", true);
			this.put("GateChain Mainnet", true);
			this.put("Nova Network", true);
			this.put("SwissDLT", true);
			this.put("Six Protocol", true);
			this.put("Worldland Mainnet", true);
			this.put("Coinbit Mainnet", true);
			this.put("Uptick Mainnet", true);
			this.put("ENULS Testnet", true);
			this.put("Huobi ECO Chain Mainnet", true);
			this.put("ProtoJumbo Testnet", true);
			this.put("iExec Sidechain", true);
			this.put("Alyx Chain Testnet", true);
			this.put("WoopChain Mainnet", true);
			this.put("PHI Network v2", true);
			this.put("ShimmerEVM", true);
			this.put("Six Protocol Testnet", true);
			this.put("AIOZ Network", true);
			this.put("AME Chain Mainnet", true);
			this.put("Seele Mainnet", true);
			this.put("BMC Testnet", true);
			this.put("Crypto Emergency", true);
			this.put("Bitchain Mainnet", true);
			this.put("BitTorrent Chain Mainnet", true);
			this.put("VinuChain Testnet", true);
			this.put("VinuChain Network", true);
			this.put("MAP Makalu", true);
			this.put("SiriusNet V2", true);
			this.put("Scalind Testnet", true);
			this.put("LACHAIN Testnet", true);
			this.put("Deamchain Testnet", true);
			this.put("Energy Web Chain", true);
			this.put("Neonlink Mainnet", true);
			this.put("High Performance Blockchain", true);
			this.put("EgonCoin Mainnet", true);
			this.put("zkSync Era Goerli Testnet (deprecated)", true);
			this.put("Hedera Previewnet", true);
			this.put("Neurochain Testnet", true);
			this.put("Wyzth Testnet", true);
			this.put("Omax Mainnet", true);
			this.put("KCC Mainnet", true);
			this.put("KCC Testnet", true);
			this.put("DFK Chain Test", true);
			this.put("Theta Mainnet", true);
			this.put("Theta Testnet", true);
			this.put("Nativ3 Mainnet", true);
			this.put("Ozone Chain Testnet", true);
			this.put("SX Network Mainnet", true);
			this.put("PGN (Public Goods Network)", true);
			this.put("Geso Verse", true);
			this.put("ARZIO Chain", true);
			this.put("Camino C-Chain", true);
			this.put("Columbus Test Network", true);
			this.put("Double-A Chain Mainnet", true);
			this.put("Double-A Chain Testnet", true);
			this.put("Gear Zero Network Mainnet", true);
			this.put("F(x)Core Mainnet Network", true);
			this.put("Candle", true);
			this.put("MetaChain Mainnet", true);
			this.put("Acala Mandala Testnet TC9", true);
			this.put("Karura Network Testnet", true);
			this.put("Acala Network Testnet", true);
			this.put("Vine Testnet", true);
			this.put("Graphlinq Blockchain Mainnet", true);
			this.put("Avocado", true);
			this.put("SX Network Testnet", true);
			this.put("Endurance Smart Chain Mainnet", true);
			this.put("Kalichain Testnet", true);
			this.put("Kalichain", true);
			this.put("Pixie Chain Testnet", true);
			this.put("Karura Network", true);
			this.put("Highbury", true);
			this.put("Shibarium Beta", true);
			this.put("Blucrates", true);
			this.put("Script Testnet", true);
			this.put("Acala Network", true);
			this.put("Patex", true);
			this.put("Lucid Blockchain", true);
			this.put("Haven1 Testnet", true);
			this.put("Callisto Mainnet", true);
			this.put("Taraxa Mainnet", true);
			this.put("Taraxa Testnet", true);
			this.put("Wanchain", true);
			this.put("Rinia Testnet", true);
			this.put("Mode Testnet", true);
			this.put("Yidark Chain Mainnet", true);
			this.put("Lyra Chain", true);
			this.put("BTC20 Smart Chain", true);
			this.put("Oort Mainnet", true);
			this.put("Oort Ascraeus", true);
			this.put("TOP Mainnet EVM", true);
			this.put("Memo Smart Chain Mainnet", true);
			this.put("eLiberty Mainnet", true);
			this.put("5ireChain Thunder", true);
			this.put("Wanchain Testnet", true);
			this.put("Tectum Emission Token", true);
			this.put("T-EKTA", true);
			this.put("Newton Testnet", true);
			this.put("Evrice Network", true);
			this.put("Newton", true);
			this.put("CLV Parachain", true);
			this.put("ShimmerEVM Testnet", true);
			this.put("Mintara Testnet", true);
			this.put("Mintara Mainnet", true);
			this.put("BLXq Testnet", true);
			this.put("BLXq Mainnet", true);
			this.put("AmStar Testnet", true);
			this.put("Symplexia Smart Chain", true);
			this.put("Origin Testnet", true);
			this.put("Ultron Testnet", true);
			this.put("Ultron Mainnet", true);
			this.put("Step Network", true);
			this.put("OM Platform Mainnet", true);
			this.put("Dogether Mainnet", true);
			this.put("Moonbase Alpha", true);
			this.put("Swisstronik Testnet", true);
			this.put("Alyx Mainnet", true);
			this.put("AIA Testnet", true);
			this.put("Elysium Testnet", true);
			this.put("Elysium Mainnet", true);
			this.put("Blitz Subnet", true);
			this.put("CIC Chain Mainnet", true);
			this.put("AmStar Mainnet", true);
			this.put("Joseon Mainnet", true);
			this.put("Rikeza Network Mainnet", true);
			this.put("GIL Testnet", true);
			this.put("Ctex Scan Blockchain", true);
			this.put("LUDAN Mainnet", true);
			this.put("TBSI Mainnet", true);
			this.put("TBSI Testnet", true);
			this.put("Palette Chain Mainnet", true);
			this.put("Gauss Mainnet", true);
			this.put("Kerleano", true);
			this.put("Cube Chain Mainnet", true);
			this.put("WhiteBIT Network", true);
			this.put("Lightlink Phoenix Mainnet", true);
			this.put("Lightlink Pegasus Testnet", true);
			this.put("Bitcichain Mainnet", true);
			this.put("Bitcichain Testnet", true);
			this.put("Merkle Scan", true);
			this.put("Scalind", true);
			this.put("Ruby Smart Chain Testnet", true);
			this.put("ONUS Chain Testnet", true);
			this.put("Super Smart Chain Testnet", true);
			this.put("Atelier", true);
			this.put("RedeCoin", true);
			this.put("ONUS Chain Mainnet", true);
			this.put("EtherGem", true);
			this.put("Ekta", true);
			this.put("Kyoto Testnet", true);
			this.put("PublicMint Mainnet", true);
			this.put("Beresheet BereEVM Testnet", true);
			this.put("Kiwi Subnet", true);
			this.put("Shrapnel Testnet", true);
			this.put("OriginTrail Parachain", true);
			this.put("Shrapnel Subnet", true);
			this.put("Stratos Testnet", true);
			this.put("Stratos", true);
			this.put("Exosama Network", true);
			this.put("Metaplayerone Dubai Testnet", true);
			this.put("Findora Mainnet", true);
			this.put("Findora Testnet", true);
			this.put("Bitcoin EVM", true);
			this.put("Evanesco Mainnet", true);
			this.put("Ebro Network", true);
			this.put("Altcoinchain", true);
			this.put("TCG Verse Mainnet", true);
			this.put("Unicorn Ultra Nebulas Testnet", true);
			this.put("Fraxtal Testnet", true);
			this.put("Kortho Mainnet", true);
			this.put("PoCRNet", true);
			this.put("Redlight Chain Mainnet", true);
			this.put("WhiteBIT Network Testnet", true);
			this.put("Morph Testnet", true);
			this.put("K-LAOS", true);
			this.put("Boba Network Goerli Testnet", true);
			this.put("BitYuan Mainnet", true);
			this.put("CENNZnet Nikau", true);
			this.put("Canxium Mainnet", true);
			this.put("Immu3 EVM", true);
			this.put("Vulture EVM Beta", true);
			this.put("Dubxcoin network", true);
			this.put("Dubxcoin testnet", true);
			this.put("ZCore Testnet", true);
			this.put("Web3Q Testnet", true);
			this.put("Web3Q Galileo", true);
			this.put("Paribu Net Mainnet", true);
			this.put("SecureChain Testnet", true);
			this.put("Paribu Net Testnet", true);
			this.put("JFIN Chain", true);
			this.put("PandoProject Mainnet", true);
			this.put("PandoProject Testnet", true);
			this.put("Botanix Testnet", true);
			this.put("iChain Network", true);
			this.put("Jouleverse Mainnet", true);
			this.put("Empire Network", true);
			this.put("SenjePowers Testnet", true);
			this.put("Crossbell", true);
			this.put("KalyChain Mainnet", true);
			this.put("KalyChain Testnet", true);
			this.put("DOS Tesnet", true);
			this.put("YuanChain Mainnet", true);
			this.put("Ozone Chain Mainnet", true);
			this.put("X1 Fastnet", true);
			this.put("Muster Mainnet", true);
			this.put("Fastex Chain (Bahamut) Oasis Testnet", true);
			this.put("AIOZ Network Testnet", true);
			this.put("Tipboxcoin Testnet", true);
			this.put("Credit Smart Chain Mainnet", true);
			this.put("Orderly Sepolia Testnet", true);
			this.put("IoTeX Network Testnet", true);
			this.put("BlackFort Exchange Network Testnet", true);
			this.put("Globel Chain", true);
			this.put("Venidium Mainnet", true);
			this.put("Humanode Mainnet", true);
			this.put("VEX EVM TESTNET", true);
			this.put("Nahmii Mainnet", true);
			this.put("Chain Verse Mainnet", true);
			this.put("Tanssi EVM ContainerChain", true);
			this.put("Hika Network Testnet", true);
			this.put("SatoshiChain Testnet", true);
			this.put("Tres Testnet", true);
			this.put("Cascadia Testnet", true);
			this.put("UPTN", true);
			this.put("Pixie Chain Mainnet", true);
			this.put("Latest Chain Testnet", true);
			this.put("Cybria Mainnet", true);
			this.put("Cybria Testnet", true);
			this.put("PAXB Mainnet", true);
			this.put("Gold Smart Chain Mainnet", true);
			this.put("Tomb Chain Mainnet", true);
			this.put("Ella the heart", true);
			this.put("Planq Mainnet", true);
			this.put("Nume", true);
			this.put("Shyft Mainnet", true);
			this.put("MEVerse Chain Mainnet", true);
			this.put("ADIL Testnet", true);
			this.put("Adil Chain V2 Mainnet", true);
			this.put("The Root Network - Mainnet", true);
			this.put("The Root Network - Porcini Testnet", true);
			this.put("Bitrock Testnet", true);
			this.put("Hela Official Runtime Mainnet", true);
			this.put("Storagechain Mainnet", true);
			this.put("Storagechain Testnet", true);
			this.put("TMY Chain", true);
			this.put("MARO Blockchain Mainnet", true);
			this.put("XANAChain", true);
			this.put("Vyvo Smart Chain", true);
			this.put("Giant Mammoth Mainnet", true);
			this.put("bloxberg", true);
			this.put("Codefin Mainnet", true);
			this.put("Evoke Mainnet", true);
			this.put("Rangers Protocol Testnet Robin", true);
			this.put("Oort MainnetDev", true);
			this.put("MainnetZ Testnet", true);
			this.put("Carbon EVM", true);
			this.put("Carbon EVM Testnet", true);
			this.put("Dogelayer Mainnet", true);
			this.put("Combo Mainnet", true);
			this.put("Agung Network", true);
			this.put("AltLayer Testnet", true);
			this.put("Arthera Mainnet", true);
			this.put("Worldland Testnet", true);
			this.put("Numbers Mainnet", true);
			this.put("Numbers Testnet", true);
			this.put("WAGMI", true);
			this.put("Sardis Testnet", true);
			this.put("SanR Chain", true);
			this.put("Polygon Supernet Arianee", true);
			this.put("BRC Chain Mainnet", true);
			this.put("Step Testnet", true);
			this.put("Credit Smart Chain", true);
			this.put("Phoenix Mainnet", true);
			this.put("Humanode Testnet 5 Israfel", true);
			this.put("Immutable zkEVM Devnet", true);
			this.put("LoopNetwork Mainnet", true);
			this.put("Genesys Mainnet", true);
			this.put("IRIShub Testnet", true);
			this.put("AirDAO Mainnet", true);
			this.put("IVAR Chain Testnet", true);
			this.put("Redstone Holesky Testnet", true);
			this.put("G8Chain Mainnet", true);
			this.put("Palette Chain Testnet", true);
			this.put("Smart Trade Networks", true);
			this.put("G8Chain Testnet", true);
			this.put("MXC zkEVM Mainnet", true);
			this.put("HOME Verse Mainnet", true);
			this.put("Camelark Mainnet", true);
			this.put("Callisto Testnet", true);
			this.put("P12 Chain", true);
			this.put("CENNZnet Azalea", true);
			this.put("omChain Mainnet", true);
			this.put("BSL Mainnet", true);
			this.put("AirDAO Testnet", true);
			this.put("Nautilus Mainnet", true);
			this.put("GoldXChain Testnet", true);
			this.put("MAP Mainnet", true);
			this.put("MintMe.com Coin", true);
			this.put("Hammer Chain Mainnet", true);
			this.put("MCH Verse Mainnet", true);
			this.put("Cerium Testnet", true);
			this.put("CloudTx Mainnet", true);
			this.put("CloudTx Testnet", true);
			this.put("Evoke Testnet", true);
			this.put("Fusion Mainnet", true);
			this.put("Zilliqa EVM Isolated Server", true);
			this.put("Cloudverse Subnet", true);
			this.put("Aves Mainnet", true);
			this.put("Zilliqa EVM Devnet", true);
			this.put("Zilliqa 2 EVM Devnet", true);
			this.put("Mode", true);
			this.put("J2O Taro", true);
			this.put("Q Mainnet", true);
			this.put("Q Testnet", true);
			this.put("ConnectorManager", true);
			this.put("ConnectorManager Robin", true);
			this.put("Energi Mainnet", true);
			this.put("OHO Mainnet", true);
			this.put("Opulent-X BETA", true);
			this.put("GoldXChain Mainnet", true);
			this.put("Gesoten Verse Testnet", true);
			this.put("Kinto Testnet", true);
			this.put("Celo Alfajores Testnet", true);
			this.put("Deelance Mainnet", true);
			this.put("Fusion Testnet", true);
			this.put("REI Network", true);
			this.put("Energi Testnet", true);
			this.put("Yooldo Verse Mainnet", true);
			this.put("Yooldo Verse Testnet", true);
			this.put("Sardis Mainnet", true);
			this.put("DFK Chain", true);
			this.put("Haqq Chain Testnet", true);
			this.put("Titan", true);
			this.put("REI Chain Mainnet", true);
			this.put("REI Chain Testnet", true);
			this.put("VELO Labs Mainnet", true);
			this.put("Rollux Testnet", true);
			this.put("Sepolia PGN (Public Goods Network)", true);
			this.put("Genesys Code Mainnet", true);
			this.put("Celo Baklava Testnet", true);
			this.put("eCredits Mainnet", true);
			this.put("eCredits Testnet", true);
			this.put("Scolcoin Mainnet", true);
			this.put("Janus Testnet", true);
			this.put("DM2 Verse Mainnet", true);
			this.put("Thinkium Mainnet Chain 1", true);
			this.put("Thinkium Mainnet Chain 2", true);
			this.put("Thinkium Mainnet Chain 103", true);
			this.put("Godwoken Mainnet", true);
			this.put("Grok Chain Mainnet", true);
			this.put("Energy Web Volta Testnet", true);
			this.put("Mixin Virtual Machine", true);
			this.put("Firenze test network", true);
			this.put("Amplify Subnet", true);
			this.put("Bulletin Subnet", true);
			this.put("Conduit Subnet", true);
			this.put("Gold Smart Chain Testnet", true);
			this.put("Nordek Mainnet", true);
			this.put("Smart Layer Network Testnet", true);
			this.put("Nautilus Proteus Testnet", true);
			this.put("IVAR Chain Mainnet", true);
			this.put("Combo Testnet", true);
			this.put("Lambda Testnet", true);
			this.put("UB Smart Chain", true);
			this.put("Crystaleum", true);
			this.put("QuarkChain Devnet Shard 3", true);
			this.put("Metachain One Mainnet", true);
			this.put("ADIL Devnet", true);
			this.put("Taiko Katla L2", true);
			this.put("Bitica Chain Mainnet", true);
			this.put("Alaya Mainnet", true);
			this.put("Decimal Smart Chain Testnet", true);
			this.put("PlatON Mainnet", true);
			this.put("Mas Mainnet", true);
			this.put("Reapchain Mainnet", true);
			this.put("Reapchain Testnet", true);
			this.put("CONET Holesky", true);
			this.put("ARTIS sigma1", true);
			this.put("ARTIS Testnet tau1", true);
			this.put("Saakuru Testnet", true);
			this.put("CMP-Mainnet", true);
			this.put("Gear Zero Network Testnet", true);
			this.put("EgonCoin Testnet", true);
			this.put("TTcoin Smart Chain Mainnet", true);
			this.put("Aves Testnet", true);
			this.put("Nativ3 Testnet", true);
			this.put("Oone Chain Testnet", true);
			this.put("Oone Chain Devnet", true);
			this.put("Digit Soul Smart Chain 2", true);
			this.put("HAPchain Testnet", true);
			this.put("Metal C-Chain", true);
			this.put("Metal Tahoe C-Chain", true);
			this.put("Tipboxcoin Mainnet", true);
			this.put("Markr Go", true);
			this.put("Dexalot Subnet Testnet", true);
			this.put("Dexalot Subnet", true);
			this.put("Patex Sepolia Testnet", true);
			this.put("Ultra Pro Mainnet", true);
			this.put("CMP-Testnet", true);
			this.put("ethereum Fair", true);
			this.put("ALL Mainnet", true);
			this.put("Vision - Vpioneer Test Chain", true);
			this.put("Hela Official Runtime Testnet", true);
			this.put("Miexs Smartchain", true);
			this.put("Modularium", true);
			this.put("OctaSpace", true);
			this.put("Dodao", true);
			this.put("BlocX Mainnet", true);
			this.put("Vision - Mainnet", true);
			this.put("Astria EVM Dusknet", true);
			this.put("Ecrox Chain Mainnet", true);
			this.put("Tiltyard Subnet", true);
			this.put("Plian Mainnet Main", true);
			this.put("PlatON Dev Testnet2", true);
			this.put("DPU Chain", true);
			this.put("AltLayer Zero Gas Network", true);
			this.put("MXC Wannsee zkEVM Testnet", true);
			this.put("Imversed Mainnet", true);
			this.put("Saakuru Mainnet", true);
			this.put("QL1 Testnet", true);
			this.put("Plian Mainnet Subchain 1", true);
			this.put("HAPchain", true);
			this.put("XCAP", true);
			this.put("Milvine", true);
			this.put("Plian Testnet Subchain 1", true);
			this.put("Anduschain Mainnet", true);
			this.put("Plian Testnet Main", true);
			this.put("SmartMesh Mainnet", true);
			this.put("Excelon Mainnet", true);
			this.put("Aquachain", true);
			this.put("Frame Testnet", true);
			this.put("T.E.A.M Blockchain", true);
			this.put("Gather Mainnet Network", true);
			this.put("Kanazawa", true);
			this.put("Neon EVM Devnet", true);
			this.put("Razor Skale Chain", true);
			this.put("OneLedger Mainnet", true);
			this.put("Meld", true);
			this.put("SKALE Calypso Hub Testnet", true);
			this.put("SKALE Europa Hub Testnet", true);
			this.put("SKALE Nebula Hub Testnet", true);
			this.put("CyberdeckNet", true);
			this.put("HUMAN Protocol", true);
			this.put("SKALE Titan Hub", true);
			this.put("Chaos (SKALE Testnet)", true);
			this.put("RaptorChain", true);
			this.put("SKALE Nebula Hub", true);
			this.put("SKALE Titan Hub Testnet", true);
			this.put("SKALE Calypso Hub", true);
			this.put("Harmony Mainnet Shard 1", true);
			this.put("Harmony Testnet Shard 0", true);
			this.put("Harmony Testnet Shard 1", true);
			this.put("Harmony Devnet Shard 0", true);
			this.put("Harmony Devnet Shard 1", true);
			this.put("SKALE Europa Hub", true);
			this.put("Ancient8 Testnet (deprecated)", true);
			this.put("OneLedger Testnet Frankenstein", true);
			this.put("Palm Testnet", true);
			this.put("Palm", true);
			this.put("Ntity Mainnet", true);
			this.put("Haradev Testnet", true);

		}};

		String jsonarr = HttpRequestUtils.getBodyUsingGETUrlRequest("https://chainid.network/chains.json");
		if (jsonarr.startsWith("[{")) {
			LOGGER.info("JSON retrieved ..");
			ExtEVMChainEntry[] arr = JSONUtils.createPOJOFromJSON(jsonarr, ExtEVMChainEntry[].class);
			if (null == arr) {
				LOGGER.error("Unable to parse JSON");
				SystemUtils.halt();
			}
			for (ExtEVMChainEntry eece: arr) {
				if (debug) System.out.println("chain: " + eece.getName());
				EVMChain evmchain = chain_map.get(eece.getName());

				HashMap<String, Boolean> forestfish_nodes = new HashMap<>();
				if (null != evmchain) {
					EVMChainInfo chaininfo = EVMUtils.getEVMChainInfo(evmchain);
					if (null == chaininfo) {
						LOGGER.error("chaininfo is null for evmchain " + evmchain + "?");
						SystemUtils.halt();
					}
					if (null == chaininfo.getChainId()) {
						LOGGER.error("chaininfo id is null?");
						SystemUtils.halt();
					}
					if (null == eece.getChainId()) {
						LOGGER.error("eece chaininfo id is null?");
						SystemUtils.halt();
					}

					if (null != skipchains.get(eece.getName())) {
						// known and skip
						//System.out.println("Skipping chain: " + eece.getName());
					} else {

						// Sanitycheck
						if (!chaininfo.getChainId().equals(eece.getChainId())) {
							LOGGER.warn("Incorrect chain ID for " + chaininfo.getChainName() + "?");
							LOGGER.warn("forestfish ID: " + chaininfo.getChainId());
							LOGGER.warn("chainlist ID: " + eece.getChainId());
							SystemUtils.halt();
						}

						for (String nodeURL: chaininfo.getNodeURLs()) {
							if (debug) System.out.println(" - forestfish node: " + nodeURL);
							forestfish_nodes.put(nodeURL, true);
						}
						if (debug) System.out.println("----------------------------------");
						int newnode_count = 0;
						for (String nodeURL: eece.getRpc()) {
							if (nodeURL.startsWith("http")) {
								if (!nodeURL.contains("API_KEY")) {
									if (null == forestfish_nodes.get(nodeURL)) {
										if (null == skipnodeurls.get(nodeURL)) {
											Web3j web3j_cand = Web3j.build(new HttpService(nodeURL));
											Long latestblocknr = EVMUtils.getLatestBlockNumberFromNodeAsHealthCheck(evmchain, nodeURL, web3j_cand);
											if ((null != latestblocknr) && (latestblocknr>0L)) {
												System.out.println("this.add(\"" + nodeURL + "\");");
												newnode_count++;
											}
										}
									}
								}
							}
						}

						if (newnode_count > 0) {
							LOGGER.info("Add the new " + newnode_count + " nodes for networks.put(EVMChain." + evmchain.toString() + ", in BlockchainDetailsEVM and re-run");
							SystemUtils.halt();
						}
					}
				} else {

					if (null != skipchains.get(eece.getName())) {
						// known and skip
						//System.out.println("Skipping chain: " + eece.getName());
					} else {

						int nodeCount = 0;
						int activeNodeCount = 0;
						for (String nodeURL: eece.getRpc()) {
							if (nodeURL.startsWith("http")) {
								if (!nodeURL.contains("API_KEY")) {
									if (null == skipnodeurls.get(nodeURL)) {
										nodeCount++;
										Web3j web3j_cand = Web3j.build(new HttpService(nodeURL));
										Long latestblocknr = EVMUtils.getLatestBlockNumberFromNodeAsHealthCheck(evmchain, nodeURL, web3j_cand);
										if ((null != latestblocknr) && (latestblocknr>0L)) {
											activeNodeCount++;
										}
									}
								}
							}
						}

						if (activeNodeCount == 1) {
							System.out.println("NEW active/candidate chain: " + eece.getName() + " [activeNodeCount: " + activeNodeCount + "/" + nodeCount + "]");
							System.out.println("  - chainid   : " + eece.getChainId());
							System.out.println("  - explorers : " + eece.getExplorers());
							System.out.println("  - faucets   : " + eece.getFaucets());
							System.out.println("  - rpcs      : " + eece.getRpc());
							System.out.println("  - currency  : " + eece.getNativeCurrency().getSymbol());

							// temp
							FilesUtils.appendToFileUNIXNoException("this.put(\"" + eece.getName() + "\", true);", "skipped_chains.singlenode");
						} else if (activeNodeCount > 1) {
							System.out.println("NEW multinode active/candidate chain: " + eece.getName() + " [activeNodeCount: " + activeNodeCount + "/" + nodeCount + "]");
							System.out.println("  - chainid   : " + eece.getChainId());
							System.out.println("  - explorers : " + eece.getExplorers());
							System.out.println("  - faucets   : " + eece.getFaucets());
							System.out.println("  - rpcs      : " + eece.getRpc());
							System.out.println("  - currency  : " + eece.getNativeCurrency().getSymbol());

							// temp
							FilesUtils.appendToFileUNIXNoException("this.put(\"" + eece.getName() + "\", true);", "skipped_chains.multinode");
						}

						String chain_shortname = null;
						String chain_enum = null;

						if (false ||
								eece.getName().toLowerCase().contains("test") ||
								eece.getName().toLowerCase().contains("devnet") ||
								eece.getName().toLowerCase().contains("stage") ||
								eece.getName().toLowerCase().contains("staging") ||
								eece.getName().toLowerCase().contains("demo") ||
								eece.getName().toLowerCase().contains("goerli") ||
								eece.getName().toLowerCase().contains("sepolia") ||
								eece.getName().toLowerCase().contains("holesky") ||
								false) {
							chain_shortname = eece.getName().split(" ")[0].toLowerCase().replace("(","").replace(")","") + "_test";
							chain_enum = eece.getName().split(" ")[0].toUpperCase().replace("(","").replace(")","") + "TEST";
						} else {
							chain_shortname = eece.getName().split(" ")[0].toLowerCase().replace("(","").replace(")","");
							chain_enum = eece.getName().split(" ")[0].toUpperCase().replace("(","").replace(")","");
						}

						// grab 1 explorer
						String explorer = "<TODO>";
						if (null != eece.getExplorers()) {
							for (HashMap<String, String> hm: eece.getExplorers()) {
								explorer = hm.get("url");
							}
						}

						// grab 1 faucet
						String faucet = "<TODO>";
						if (null != eece.getFaucets()) {
							for (String s: eece.getFaucets()) {
								faucet = s;
							}
						}

						if (activeNodeCount >= 1) {
							System.out.println("");
							System.out.println("		// " + chain_shortname + "\n"
									+ "		EVMChainInfo " + chain_shortname + " = new EVMChainInfo(\n"
									+ "				EVMChain." + chain_enum + ".toString(), \n"
									+ "				\"" + eece.getName() + "\", \n"
									+ "				" + eece.getChainId() + "L, \n"
									+ "				BlockchainType.PUBLIC.toString(),\n"
									+ "				new EVMCurrency(\"" + eece.getName() + " Gas Token\", \"" + eece.getNativeCurrency().getSymbol() + "\", 18), \n"
									+ "				EVMPriceMechanism.LEGACY.toString(),30,\n"
									+ "				\"30000000000\", //30 gwei\n"
									+ "				null, // enforced min gasprice\n"
									+ "				\"300000\", //300k units\n"
									+ "				new ArrayList<String>() {{\n"
									+ "					this.add(\"" + eece.getRpc().get(0) + "\");\n"
									+ "				}}, \n"
									+ "				new ArrayList<String>(), // archive nodes (if available)\n"
									+ "				new ArrayList<String>(),\n"
									+ "				new ArrayList<String>(),\n"
									+ "				new ArrayList<String>() {{\n"
									+ "					this.add(\"" + explorer + "\");\n"
									+ "				}},\n"
									+ "				new ArrayList<String>() {{\n"
									+ "					this.add(\"" + faucet + "\");\n"
									+ "				}},\n"
									+ "				new ArrayList<String>() {{\n"
									+ "					this.add(\"https://chainlist.org/chain/" + eece.getChainId() + "\");\n"
									+ "				}},\n"
									+ "				BlockchainTokenDetailsEVM.generateDummyTokenIndex(),\n"
									+ "				BlockchainTokenDetailsEVM.generateDummyNFTIndex());\n"
									+ "		networks.put(EVMChain." + chain_enum + ", " + chain_shortname + ");");
							System.out.println("");
							System.out.println("");
							System.out.println("this.put(\"" + eece.getName() + "\", EVMChain." + chain_enum + ");");

							// Add one entry at a time
							SystemUtils.halt();
						}

					}
				}	
			}

		} else {
			LOGGER.error("Unable to get a proper JSON reply");
			SystemUtils.halt();
		}

		LOGGER.info("fin.all.rpc.nodes.up.to.date");
	}

}
